### ISSUE TITLE
translation string update

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10328]
Hi

Because the "Options" menu is removed, the following translation string needs to be updated

From

`To improve the user experience, we would like to collect anonymous statistics on the features you use. We will only record what features you access and how often you do it. We will neither collect any personal data nor the content of bibliographic items. If you choose to allow data collection, you can later disable it via Options -> Preferences -> General.`

To

`To improve the user experience, we would like to collect anonymous statistics on the features you use. We will only record what features you access and how often you do it. We will neither collect any personal data nor the content of bibliographic items. If you choose to allow data collection, you can later disable it via File -> Preferences -> General.`

**Comment by koppor** [comment]
Well-spotted! Thank you for the hint. I fixed it at https://github.com/JabRef/jabref/pull/10331. Let's see, if the fix really works. With translation strings inside JabRef one newer knows if the initial try works ^^.

**Comment by the-dino-girl** [comment]
Does there need to be a sync with crowdin maybe?
It's still the same there.

**Comment by koppor** [comment]
You are experiencing the "development workflow" of JabRef: On a change, first a PR his made (this, I have done). Then, that PR needs to be reviewed - and approved (!) by two developers. The reason is that the contributor might have overlooked something. The two reviewers ensure that the global JabRef goals are met. After two approvals, the PR is merged. Then, it appears on Crowdin. -- Sometimes, only one developer agrees and directly merges the PR. This happens by small PRs with a low risk (to reduce reviewing load at the maintainers). -- This is the longer version of "I fixed it at https://github.com/JabRef/jabref/pull/10331" 😅 

In the concrete case at hand, there was no review yet. I think, that will happen today.

One more thing: When a release is not "in sight", we disable Crowdin to reduce the number of open PRs. We will re-enable synchronization after the PRs is merged. Furthermore, we will think about some auto-merge of the Crowdin-PRs to reduce load on our side.

More text on the review process at https://devdocs.jabref.org/teaching#process-for-contributions.

**Comment by the-dino-girl** [comment]
Wow! I had no idea all these checks were done. It seems like a lot of work for just 1 small thing!

**Comment by koppor** [comment]
> Wow! I had no idea all these checks were done. It seems like a lot of work for just 1 small thing!

We have (at least) two decision drivers:

- There should be one development process with as less as possible exceptions.
- The code in the `main` branch should be of high quality (both maintainability and functionality)

**Comment by Jaovitosr** [comment]
Kamino cloned this issue to [Jaovitosr/Chatbot](https://github.com/Jaovitosr/Chatbot/issues/2)
