### ISSUE TITLE
Detached Dropdown for Menu Buttons on Screen in Portrait Mode

### ISSUE THREAD

**Issue by St0rml** [JabRef/jabref#10664]
### JabRef version

5.11 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Fedora Linux 39, GNOME 45, Wayland Session

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open Jabref
2. Move Jabref window to rotated display (In this case 1080x1920)
3. Click on any menu button to open dropdown

### Appendix

![Screenshot from 2023-11-25 15-11-03](https://github.com/JabRef/jabref/assets/61873910/ae25d7b0-8e4a-4477-806e-735e25c35a18)
![Screencast from 2023-11-25 15-31-11.webm](https://github.com/JabRef/jabref/assets/61873910/0227218a-dc94-400f-a359-ae0b23a0ef42)
<details>
This issues seems to depend on the position of the jabref window on the screen. I suspect this to be dependent of the relative alignment between my two displays, because when I move the window above the edge of the landscape-mode display, this issue appears. However below this edge everything is back to normal. Also I'm not sure if this is actually a Jabref Problem or JavaFX, as I also have troubles with the issues described in Issue #9426 
</details>

**Comment by Siedlerchr** [comment]
Can you try the latest development version? Because we upgraded to javafx21 in the meantime and it could be fixed there

**Comment by St0rml** [comment]
I tried the portable version
```JabRef 5.12--2023-11-22--43364b8
Linux 6.5.12-300.fc39.x86_64 amd64 
Java 21.0.1 
JavaFX 21.0.1+6```
and the issues persists.

**Comment by Siedlerchr** [comment]
Can you try this version ? https://builds.jabref.org/pull/10808/merge

**Comment by St0rml** [comment]
The issue persists for me.
```
JabRef 5.13-PullRequest10808.81--2024-01-20--34082ca
Linux 6.6.11-200.fc39.x86_64 amd64 
Java 21.0.1 
JavaFX 21.0.2+5
```
_I'm not sure if it helps, but it does not seem to by nvidia-specific, as I moved away from Nvidia GPUs in the meantime..._

**Comment by Siedlerchr** [comment]
We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by koppor** [comment]
This somehow refs https://github.com/JabRef/jabref/issues/10716#issuecomment-2003655683.

**Comment by Siedlerchr** [comment]
Nope this is linux here and not mac

**Comment by koppor** [comment]
@St0rml could you try a version of https://builds.jabref.org/jdk-ea/? There, we build using the most recent JavaFX development vresion. Maybe, it is fixed there.

**Comment by St0rml** [comment]
I tried the portable version
```
JabRef 5.14--2024-04-10--aa0fa84
Linux 6.8.4-200.fc39.x86_64 amd64 
Java 22 
JavaFX 23-ea+12
```
Sadly, the issue is still there.

**Comment by koppor** [comment]
@St0rml Is there an easy script to get your configuration locally, too? Think, we need to fire up a virutal machine and neither Docker nor WSL2 help here, too.
