### ISSUE TITLE
The entry preview is not related to the opening one.

### ISSUE THREAD

**Issue by Aldous-Arcane** [JabRef/jabref#10753]
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11 22H2

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. double click an arbitrary entry;
<img width="920" alt="图片1" src="https://github.com/JabRef/jabref/assets/103487046/46c84992-7132-4a03-93ef-b98d441e63b7">
2. the preview tab is not that of the openning entry (in fackt it belongs to the last chosen one), but the other tabs is displayed normally;
<img width="960" alt="图片2" src="https://github.com/JabRef/jabref/assets/103487046/e8b97435-01bd-4c25-8e42-063fcafe54d4">
3. "close and re-open" the entry windows is useless. 

### Appendix

* The preview is not related to my entry, in fact it is my last

**Comment by Siedlerchr** [comment]
@HoussemNasri  Didn't you recently fix that?

**Comment by HoussemNasri** [comment]
Yep, should be fixed in the latest development version: https://builds.jabref.org/main/

**Comment by HoussemNasri** [comment]
@Aldous-Arcane Can you confirm if the issue is fixed in the latest development version?

**Comment by Aldous-Arcane** [comment]
> @Aldous-Arcane Can you confirm if the issue is fixed in the latest development version?

I'm sure it still happens occasionally in the latest version 5.12. In most cases, clicking the other entry and re-clicking the last one or using the up and down arrow keys back and forth can solve this problem.

**Comment by HoussemNasri** [comment]
How about 5.13?

**Comment by Aldous-Arcane** [comment]
> How about 5.13?

I have used the 5.13 two days. It works well, and the bug never happened.

**Comment by HoussemNasri** [comment]
Excellent! Then we should close this one.
