### ISSUE TITLE
Cleanup - rename PDF does not work

### ISSUE THREAD

**Issue by leezu** [JabRef/jabref#1251]
JabRef version 3.3 on Linux, but was also not working for me at least in 3.2

Steps to reproduce:

1. Have some entry with a linked PDF
2. Use the cleanup entries functionality and select rename PDF or ask jabref to automatically download a PDF for the entry
3. The entry does not get renamed / is downloaded and saved with \bibtexkey.pdf instead of \bibtexkey\begin{title} - \format[RemoveBrackets]{\title}\end{title}.pdf .

Also if the file is not named as the \bibtexkey (e.g. if its named uiae.pdf) no renaming happens.

I am not sure, if I misunderstood how the feature is working, but jabref only tells, that no cleanup of any entries is necessary, even though not a single file follows the \bibtexkey\begin{title} - \format[RemoveBrackets]{\title}\end{title}.pdf pattern.

Thank you for developing this awesome software.

**Comment by tobiasdiez** [comment]
There was a problem that changes of the format specified under Preferences -> Import didn't carried over to the cleanup process. Restarting JabRef should fix this. Make sure that the correct rename format is displayed in the cleanup dialog under "File format pattern: ...".

If this also don't solve your problem, then please post the file field of your bibtex entries and the file-related configurations under File -> Database properties.

**Comment by leezu** [comment]
So I created a new bib with only one PDF downloaded from arXiv ( http://arxiv.org/abs/1603.05382 ).

The File format pattern in the settings is: 
> \bibtexkey\begin{title} - \format[RemoveBrackets]{\title}\end{title}

The file field of the entry is
>  file           = {:Zhaba2016.pdf:PDF}

![jabref1](https://cloud.githubusercontent.com/assets/946903/14696212/c7c8019c-07ab-11e6-97ba-bec674f41df1.png)
![jabref2](https://cloud.githubusercontent.com/assets/946903/14696213/c7ca2abc-07ab-11e6-98d9-f269a6418f25.png)

**Comment by tobiasdiez** [comment]
Thank you for the follow up. I tried to replicate the problem #1278, however without luck. Can you please try out the latest development version http://builds.jabref.org/master/. Maybe the problem was already fixed (although I doubt it).

**Comment by leezu** [comment]
I can confirm that the problem still exists with JabRef-3.4dev--snapshot--2016-04-22--master--9c07a14.jar

Thanks for helping to investigate this issue tobias.

**Comment by simonharrer** [comment]
Cannot reproduce on current master - here the rename works as expected but I use the default preferences. Can you provide a minimal example (.bib file and the pdf) and your preferences (options - preferences - export preferences)?

**Comment by tobiasdiez** [comment]
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.
