### ISSUE TITLE
add to group during import ignored

### ISSUE THREAD

**Issue by napseis** [JabRef/jabref#2191]
Hi! 

Entries added to group during import is ignored.

JabRef version 3.6 on Opensuse 42.2

Steps to reproduce:
1. import a bib file into the current database
2. from the pop up windows, select the entries and add them to an existing group
3. new entries do not belong to any group

Thanks

**Comment by AEgit** [comment]
I can't reproduce this behaviour when trying to import a bibtex file with a single or multiple entries into JabRef 3.8.2. Maybe this has already been fixed in current versions of JabRef?

@napseis: Have you tried a current version of JabRef? Does the problem still appear there?

**Comment by napseis** [comment]
hi,
Thanks for looking into it. I upgraded to JabRef 3.8.2, problem persists. Plus, it introduced another bug for me, I'll open a ticket.

**Comment by lenhard** [comment]
@napseis Can you try again with JabRef 4.0. There have been quite some hefty changes to the groups interface and there's a good chance that this has been solved.

**Comment by napseis** [comment]
hi,
I just tried it, it still doesn't work for me. Let me know if i can do something else.
Thanks

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
