### ISSUE TITLE
Fix size for HiDPI screens

### ISSUE THREAD

**Issue by cmcx** [JabRef/jabref#2409]
JabRef version 3.6  on 
Debian Linux (Sid)

It seems that Java doesn't recognize the screen setting from my window manager. It would be great to have the possibility to configure Jabref for HiDPI screens from the options menu. It is possible to use a bigger font size for the table, but the menu etc. stay quite tiny..

Steps to reproduce:

1. start Jabref in a window manager that is configured for a HiDPI screen, in my case Debian Linux (Sid) + Cinnamon (configured for HiDPI)
2. ...
3. ...

```
Put the excerpt of the log file here
```

**Comment by koppor** [comment]
Refs  #113 - "Should also work at unusual setups"

We currently have no money to pay someone for that. Thus, it depends on the availability of our free time. - If you can spend some more time, we would like to encourage you to check https://help.jabref.org/en/FAQcontributing - especially the part asking for improvement of our help pages <https://help.jabref.org/en/>. We have plenty of open issues there: https://github.com/JabRef/help.jabref.org/issues/

**Comment by stefan-kolb** [comment]
I now have a hiDPI screen. Maybe I'll have some time to investigate this in the next months.

**Comment by stefan-kolb** [comment]
Thank you for your report :+1:
This should be fixed/improved in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by koppor** [comment]
Java 9 also improves support: http://openjdk.java.net/jeps/263

(found via https://www.sitepoint.com/inside-java-9-part-i/)

**Comment by wolfgang-noichl** [comment]
JabRef 5.0--2020-03-06--2e6f433
Linux 5.4.0-31-generic amd64 
Java 13.0.2
Xfce 4.14

Here, everything looks nice except the font size is still not scaled. I think under Xfce the relevant attribute is changed by `xfconf-query -c xsettings -p /Gdk/WindowScalingFactor -s 2`, if that somehow helps. Just switching font sizes within JabRef doesn't really solve the issue if you have to switch between a non-4K notebook screen and a 4K external screen :-/

**Comment by koppor** [comment]
This refs https://github.com/JabRef/jabref/issues/5498, doesn't it? - Should we open a new issue? Do you want an issue to be opened? I think, this issue does not fully match your detail @wolfgang-noichl

**Comment by wolfgang-noichl** [comment]
Yeah, I think it's the same, sorry for re-posting.
