### ISSUE TITLE
arXiv fetcher cannot deal with the "arXiv:" prefix.

### ISSUE THREAD

**Issue by vsht** [JabRef/jabref#2427]
JabRef version JabRef 3.8.1-dev--snapshot--2016-12-22--master--6f40cf8
linux 4.8.11-100.fc23.x86_64 amd64 
Java 1.8.0_51 on Fedora 23

Steps to reproduce:

1. Try to fetch infos about an arXiv preprint without removing the "arXiv:" prefix, e.g. "arXiv:0710.0994"
2. A dialog appears for a second, after which nothing happens. The status line still shows "Status: Processing 0710.0994" though.
3. If one removes the prefix, i.e. enters just "0710.0994", then everything works as expected.

In the terminal I don't see any new log messages when this happens.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest version 3.8.1.

**Comment by vsht** [comment]
I have seen the fix being committed, but somehow the problem still persists on my system also with the version 3.8.1 (with the same symptoms). Is there a way to activate some sort of debugging output, to see what happens there?

By the way, I run JabRef with Oracle Java 

```
#/media/Data/OracleJava/bin/java -version

java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```
since the it doesn't work with OpenJDK shipped with my distro

```
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b16)
OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)
```
Could this be an issue?

**Comment by Siedlerchr** [comment]
Hello, you could either start the jar file from command line or you look
for any errors in the JabRef error console

Did you make sure to try the latest dev version from builds.jabref.org ?

Am 25.12.2016 8:53 nachm. schrieb "Vladyslav Shtabovenko" <
notifications@github.com>:

**Comment by tobiasdiez** [comment]
If you put "arXiv:0710.0994" into the "Web Search" field in the side pane, then no entry is found. This is (kind of) expected behavior since JabRef only queries the ArXiv database with exactly the given search query and this database doesn't contain an entry with "arXiv:0710.0994" in the title or abstract. Thus nothing is found. I also wouldn't change this behavior as you run into other problems if the "arXiv" string is filtered (for example, looking for articles about the arXiv is no longer possible).

The preferred way to import entries from IDs is via the "BibTeX -> New entry" menu. In the lower half of the dialog you can choose the type of ID (in your case ArXiv [not present right now] or Astrophysics Data System) and insert the id there. Using "arXiv:0710.0994" works as expected here.

**Comment by vsht** [comment]
> If you put "arXiv:0710.0994" into the "Web Search" field in the side pane, then no entry is found. This is (kind of) expected behavior since JabRef only queries the ArXiv database with exactly the given search query and this database doesn't contain an entry with "arXiv:0710.0994" in the title or abstract. Thus nothing is found. I also wouldn't change this behavior as you run into other problems if the "arXiv" string is filtered (for example, looking for articles about the arXiv is no longer possible).

Ok, whatever. Until recently I was using JabRef 2.8 with LocalCopy plugin, where "arXiv:XXXX" always worked. This why I was surprised by the current behavior. If you say that it is expected, fine.

> The preferred way to import entries from IDs is via the "BibTeX -> New entry" menu. In the lower half of the dialog you can choose the type of ID (in your case ArXiv [not present right now] or Astrophysics Data System) and insert the id there. Using "arXiv:0710.0994" works as expected there.

I see. In high energy physics 99,99% of all publications are available on the arXiv, this why I'm usually using the fetcher via "Web search" directly.
