### ISSUE TITLE
Ensure that entry editor has minimal height

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#282]
Double-click on entry in table of references doesn't open entry editor. Win10, JabRef 2.11 beta4. With 2.10 entry editor opens.

**Comment by koppor** [comment]
Could you try latest 2.11 development snapshot at http://ge.tt/9Idc446?

**Comment by grimes2** [comment]
No success with 2.11dev - 2015-10-20 01.30.45

**Comment by koppor** [comment]
Do you see some output in the "Error console"? (Help -> Show error console). Check all tabs.

If not, please export your preferences (Options -> Preferences -> Export preferences), reset them (`java -jar JabRef-....jar -d all` and try again. If everything works now, your preferences are broken somehow...

**Comment by grimes2** [comment]
I've resetted the preferences. Everything works now. Preferences were broken. Thank you!

**Comment by koppor** [comment]
Could you send us the preferences? My Email-Adress should be public on the GitHub profile. Think, you are not the only one having issues with broken preferences (see #174).

**Comment by Mixopteryx** [comment]
I had the same problem. Fixed it by exporting the preferences and changing the line `<entry key="entryEditorHeight" value="4"/>` to `<entry key="entryEditorHeight" value="500"/>` and reimporting.

**Comment by tobiasdiez** [comment]
I reopen the issue since I think JabRef should prevent heights which are too small.

**Comment by matthiasgeiger** [comment]
There was a bug related to this that has been already fixed (#1450 and #1463) - but intential small sizes where not covered by this fix.

What would be a "height which is too small"? Use 10-50px minimal size to indicate that the editor is open?

**Comment by Mixopteryx** [comment]
For me 30 px seems like a sensible minimum, at least at my system (windows 7). Then I see the top menu and would know that I could just drag it up. Its still not usable for anything so I wouldn't mind a bigger minimum size.
This wasn't intentional by me. I do not know how I managed to set the size of the entry editor to 4 px in the first place. The least height I can make by dragging seem to be 297 px, so it seems to be some kind of a limit in place already.

**Comment by grimes2** [comment]
I can't minimize the entry editor in newest development version. Is this fixed already? Can't find the commit.

**Comment by stefan-kolb** [comment]
Seems to be fixed in current `master`.
