### ISSUE TITLE
Unable to add entry using DOI

### ISSUE THREAD

**Issue by glennib** [JabRef/jabref#2879]
JabRef version  on 

    JabRef 3.8.2
    windows 7 6.1 amd64 
    Java 1.8.0_121

Steps to reproduce:

1. Open JabRef
2. Click New BibTeX entry button
3. Select ID type DOI
4. Paste a DOI (have tried multiple, that have worked in the past also)

After this, the following error message appears:
    Error while fetching from DOI.
    Invalid URL

Log is attached below.

<details>
  <summary>Log File</summary>
  
  ```
11:14:02.778 [AWT-EventQueue-0] INFO  net.sf.jabref.logic.importer.OpenDatabase - Opening: C:\Users\glennbi\src\master-thesis\thesis\refs\refs.bib
11:14:40.518 [SwingWorker-pool-4-thread-2] WARN  net.sf.jabref.logic.net.URLDownload - Could not copy input
java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1109%2FOCEANSE.2009.5278104
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_121]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:153) [JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55) [JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:293) [JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:276) [JabRef-3.8.2.jar:?]
	at javax.swing.SwingWorker$1.call(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
	at javax.swing.SwingWorker.run(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1109%2FOCEANSE.2009.5278104
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_121]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_121]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:126) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:134) ~[JabRef-3.8.2.jar:?]
	... 10 more
11:14:40.518 [SwingWorker-pool-4-thread-2] WARN  net.sf.jabref.JabRefException - No localized message exception message defined. Falling back to getMessage().
net.sf.jabref.logic.importer.FetcherException: Invalid URL
	at net.sf.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:65) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:293) [JabRef-3.8.2.jar:?]
	at net.sf.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:276) [JabRef-3.8.2.jar:?]
	at javax.swing.SwingWorker$1.call(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
	at javax.swing.SwingWorker.run(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_121]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1109%2FOCEANSE.2009.5278104
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_121]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:153) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55) ~[JabRef-3.8.2.jar:?]
	... 8 more
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1109%2FOCEANSE.2009.5278104
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_121]
	at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:1.8.0_121]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[?:1.8.0_121]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:126) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.net.URLDownload.openConnection(URLDownload.java:134) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.net.URLDownload.downloadToString(URLDownload.java:153) ~[JabRef-3.8.2.jar:?]
	at net.sf.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55) ~[JabRef-3.8.2.jar:?]
	... 8 more

  ```
</details>

**Comment by glennib** [comment]
It seems like it's a `data.crossref.org` error. I've sent an email to `labs@crossref.org` regarding the issue.

**Comment by AEgit** [comment]
I can confirm this issue for both
JabRef 3.8.2
and
JabRef 4.0.0-dev--snapshot--2017-05-25--master--4c87dde9c

As a workaround until the issue is fixed you could use JabFox (https://addons.mozilla.org/en-US/firefox/addon/jabfox/), which still works (and is, at least in my opinion, more convenient than the inbuilt DOI fetcher).

**Comment by gy145** [comment]
I can confirm this issue on two of my computer, one computer has a fresh install of the JabRef 3.8.2 installed using the official installer.

**Comment by Siedlerchr** [comment]
This seems to be a problem on the CrossRef site, as we are just following the documentation here:
 http://citation.crosscite.org/docs.html

**Comment by ttpuff** [comment]
I can confirm this issue on all of my computers. Not only by DOI, but also by adding with Title search. Using ArXiv looks fine.

**Comment by Siedlerchr** [comment]
It's a problem with all services which rely on crossref.org search. I have opened an issue there and we simply have to wait until the problems are resolved.

**Comment by ninfito** [comment]
I have the same issue. Apparently, data.crossref is temporarily down. However, doi.org works.

ninfito@epsilon:> curl -LH "Accept: application/x-bibtex" https://doi.org/10.1007/s10878-013-9651-7 
@article{Haynes_2013,
        doi = {10.1007/s10878-013-9651-7},
        url = {https://doi.org/10.1007%2Fs10878-013-9651-7},
        year = 2013,
        month = {aug},
        publisher = {Springer Nature},
        volume = {30},
        number = {3},
        pages = {579--595},
        author = {Teresa W. Haynes and Michael A. Henning and Lucas C. van der Merwe and Anders Yeo},
        title = {Progress on the Murty{\textendash}Simon Conjecture on diameter-2 critical graphs: a survey},
        journal = {Journal of Combinatorial Optimization}
}ninfito@epsilon:~> 

Is it possible to implement doi.org as a second option (in case crossref fails)? 
Thanks.

**Comment by gy145** [comment]
Actually why not put a option in the software to choose between doi.org and crossref.

**Comment by ninfito** [comment]
I noticed (just now) that data.crossref.org works with the appropriate header (without semicolon at the end).

ninfito@epsilon:> curl -LH "Accept: application/x-bibtex" https://data.crossref.org/10.1007/s10878-013-9651-7 

@article{Haynes_2013,
        doi = {10.1007/s10878-013-9651-7},
        url = {https://doi.org/10.1007%2Fs10878-013-9651-7},
        year = 2013,
        month = {aug},
        publisher = {Springer Nature},
        volume = {30},
        number = {3},
        pages = {579--595},
        author = {Teresa W. Haynes and Michael A. Henning and Lucas C. van der Merwe and Anders Yeo},
        title = {Progress on the Murty{\textendash}Simon Conjecture on diameter-2 critical graphs: a survey},
        journal = {Journal of Combinatorial Optimization}
}

**Comment by Siedlerchr** [comment]
Thanks for investigating, I will check that out.
We already query doi.org for the Doi, however it redirects you to a mirror
which is in this case crossref.org

Am 04.06.2017 9:26 nachm. schrieb "ninfito" <notifications@github.com>:

**Comment by Siedlerchr** [comment]
Ah I found the problem. In JabRef we still use http instead of https for acesssing DOI.

**Comment by egorpugin** [comment]
Any quick fixes for this in 3.8.2?

**Comment by ninfito** [comment]
@Siedlerchr, I'm not sure if the protocol used (http vs https) is important in order to solve the issue. For example, by forcing the http version 1.0 protocol and banning SSL/TLS negotiations, I still get bibtex (with the appropriate header).

ninfito@epsilon:> curl --http1.0 --no-ssl --no-tlsv1 --no-sslv2 --no-sslv3 -H "Accept: application/x-bibtex" data.crossref.org/10.1017/s09635483080090855
@article{RAZBOROV_2008,
        doi = {10.1017/s0963548308009085},
        url = {https://doi.org/10.1017%2Fs0963548308009085},
        year = 2008,
        month = {may},
        publisher = {Cambridge University Press ({CUP})},
        volume = {17},
        number = {04},
        author = {ALEXANDER A. RAZBOROV},
        title = {On the Minimal Density of Triangles in Graphs},
        journal = {Combinatorics, Probability and Computing}
}

**Comment by Siedlerchr** [comment]
@ninfito  I changed it to HTTPS, as you can see in the linked PR, and the issue was gone.

This should be fixed in the latest 4.0.0 snapshot, available in a couple of minutes.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by glennib** [comment]
I just installed the latest build from https://builds.jabref.org/master/ : ``JabRef_windows-x64_4_0_0-dev--snapshot--2017-06-06--master--ffb4bf98a.exe``.

Printout from version:
```
JabRef 4.0.0-dev--snapshot--2017-06-06--master--ffb4bf98a
Windows 7 6.1 amd64 
Java 1.8.0_121
```

Still get the same symptoms. Here's the log:

<details>
  <summary>Log File</summary>
  
  ```
Opening: C:\Users\glennbi\src\master-thesis\thesis\refs\refs.bib
Info cannot be found
org.jabref.logic.importer.FetcherException: Connection error
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:65)
	at org.jabref.gui.mergeentries.FetchAndMergeWorker.doInBackground(FetchAndMergeWorker.java:46)
	at org.jabref.gui.mergeentries.FetchAndMergeWorker.doInBackground(FetchAndMergeWorker.java:21)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1109%2Frobot.1991.131810
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:195)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:209)
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55)
	... 8 more
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1109%2Frobot.1991.131810
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:305)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:313)
	... 11 more

Connection error
org.jabref.logic.importer.FetcherException: Connection error
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:65)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:292)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:275)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1109%2FTCT.1960.1086720
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:195)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:209)
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55)
	... 8 more
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1109%2FTCT.1960.1086720
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:305)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:313)
	... 11 more
  ```
</details>

**Comment by Siedlerchr** [comment]
2017-06-06 10:10 GMT+02:00 Glenn Bitar <notifications@github.com>:

> j



The buld itself is fine, Commit ad69741, but somehow the build did not
update the installer files.
I just restared the build. If the installer contains this commit in its
name it's the right one

**Comment by glennib** [comment]
Not sure how long it usually takes, but they are not up to date yet

**Comment by Siedlerchr** [comment]
Sorry for the inconvnenience. The auto build did not trigger correctly. The actual build 5dcdd79 contains the fix

**Comment by AEgit** [comment]
I can confirm this has been fixed in:
JabRef 4.0.0-dev--snapshot--2017-06-06--master--5dcdd79ab

**Comment by glennib** [comment]
I can also confirm the fix in
```
JabRef 4.0.0-dev--snapshot--2017-06-06--master--5dcdd79ab
Windows 7 6.1 amd64 
Java 1.8.0_121
```

**Comment by ninfito** [comment]
@Siedlerchr, I can also confirm that this issue has been fixed. Thank you very much.
```
JabRef-4.0.0-dev--snapshot--2017-06-06--master--5dcdd79ab.jar
jre1.8.0_131 on Linux x86_64
```

**Comment by AdanRuiz** [comment]
Thanks @Siedlerchr It is working

`
JabRef_windows-x64_4_0_0-dev--snapshot--2017-06-09--master--b5f1e7d7e.exe
jre "1.8.0_91" on Windows 10 64bits`

**Comment by wolfkil** [comment]
will there be a fix for 3.8 also?

**Comment by EvgeniiFrolov** [comment]
Also interested. Any fix for 3.8?

**Comment by c-martinez** [comment]
I'm facing the same issue.
```
JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_172
```

Log says:
```
Connection error
org.jabref.logic.importer.FetcherException: Connection error
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:65)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:298)
	at org.jabref.gui.EntryTypeDialog$FetcherWorker.doInBackground(EntryTypeDialog.java:278)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: https://data.datacite.org/10.17026%2Fdans-xfe-rn2w
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:196)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:210)
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55)
	... 8 more
Caused by: java.io.FileNotFoundException: https://data.datacite.org/10.17026%2Fdans-xfe-rn2w
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:306)
	... 11 more
```

**Comment by Siedlerchr** [comment]
@c-martinez  The DOI/URL doesn't exist. This is not a problem of JabRef.

**Comment by c-martinez** [comment]
https://doi.org/10.17026/dans-xfe-rn2w resolves to https://easy.dans.knaw.nl/ui/datasets/id/easy-dataset:75828  (on a browser) -- you are right, it is not an issue with JabRef itself, rather seems like an issue with the resolved server. The error message got me confused.

Thanks!

**Comment by Siedlerchr** [comment]
JabRef only contacts doi.org for URL/doi resolving, there might be other handlers/resolvers for other specific urls (its complicated) that are not available from doi.org

**Comment by c-martinez** [comment]
You are right -- thanks for your response, I'll see if I can do something on the other end.

**Comment by rubel75** [comment]
It is pity that the same issue persists in 2019 :(
Mendeley can resolve DOI somehow, so there must be a solution to that.

**Comment by Siedlerchr** [comment]
@rubel75  Can you provide some details which type of DOI fails?
We just query doi org with the header "accept: apllication/x-bibtex"

**Comment by rubel75** [comment]
The DIO tested was: 10.1038/s41699-019-0102-x
and I used JabRef 3.8.2 (my mistake!). With the newest JabRef 4.3.1, the same DOI can be fetched without problems.
Thank you for getting back so quickly :)

**Comment by AEgit** [comment]
@rubel75
If you just switched from JabRef 3.8.2 to 4.3.1 be careful. The way groups are stored has changed from 3.8.2 to 4.3.1, so it is no longer possible to go back to 3.8.2 if your database has been saved using version 4.3.1. If you are happy with version 4.3.1 that is not a problem, but if you plan on going back, you might want to keep a backup of your old 3.8.2 database (I, for example, still use 3.8.2 due to performance issues in the newer versions).

**Comment by rubel75** [comment]
@AEgit
Thanks for the warning. I eventually get rid of groups. It seems that tags can be more flexible (not sure if it can be done in JabRef, but works in Mendeley). I noticed only one unpleasant behaviour in v4.3.1 when the entry preview take the full screen. It is perhaps related to this post https://github.com/JabRef/jabref/issues/4159, but it is manageable.
