### ISSUE TITLE
DOI search freezes Jabref 4.00 

### ISSUE THREAD

**Issue by janwcoenen** [JabRef/jabref#2905]
JabRef 4.0.0-dev--snapshot--2017-06-11--master--c711a7fdf
Mac OS X 10.12.5 x86_64 
Java 1.8.0_121

Steps to reproduce:

1. find DOI from article https://doi.org/10.1088/1741-4326/aa4feb
2. add article by DOI
3. freeze

**Comment by Siedlerchr** [comment]
Thanks for your report. On Windows I can not reproduce this.
New Entry -> I enter the doi  `10.1088/1741-4326/aa4feb`
Do you get any errors in the log?

**Comment by janwcoenen** [comment]
I have to force  Jabref to quit, so no log

Jan

**Comment by matthiasgeiger** [comment]
Can you try to run the jar version from the terminal? This should produce some log visible log statements we can hopefully use for debugging.
Thanks!

**Comment by janwcoenen** [comment]
DONE - and the jar doenst show the freeze, 
then downloaded the dmg again - still the same error, despite being the same build as the jar. 

Jan

Dr. Jan Willem Coenen
———— - - - - - - - - - - - - - - - ---------
Brauweilerweg 183		
50933 Köln
Mobil:	+491707775573
jan.w.coenen@me.com
-------- - - - - - - - - - - - - - - - ---------
http://www.jan-coenen.de

**Comment by alvesmgabriel** [comment]
Hi,
I have the same problem and the I got the follow log from terminal:
```
AI: INFO 13-06-2017 15:59, 19: Configuration file has been successfully found as resource
15:59:06.454 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/pc/file.bib
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
```
After 5 minutes, I have forced Jabref to quit. My computer:
```
JabRef 4.0.0-dev--snapshot--2017-06-11--master--c711a7fdf
Ubuntu 16.04 LTS
Java 1.8.0_131
```

Thanks.

**Comment by Siedlerchr** [comment]
@alvesmgabriel  Would you mind giving us your database file, so that can see if there is sth wrong with it?
 If you do not want it to have public avaiable, you can send us the database to developers@jabref.org

**Comment by alvesmgabriel** [comment]
@Siedlerchr, I sent to you the database file. I use the same file since previous versions of Jabref.

Thanks.

**Comment by Siedlerchr** [comment]
Thanks. Your bib files is okay.  The only thing which could happen is that there might be the "Backup found dialog hiding somewhere in the backround behind the JabRef Main window.

**Comment by Siedlerchr** [comment]
@janwcoenen  Could you please test again with the latest snaphot? Yesterday I fixed a bug which might have influences on this

**Comment by alvesmgabriel** [comment]
Hi @Siedlerchr. I tested the latest snapshot (0c006c1e1) and the problem remains. In fact, I realized that jabref freezes with any action, as when I try to edit one entry. The log from terminal is the same as I cited it previous as well as my bib file.

**Comment by janwcoenen** [comment]
Latest build  still happening

**Comment by Siedlerchr** [comment]
Can you please describe the freezing?  How does the freezing look? Does it work after some time?
There is a slight delay when you double click on an entry, so you have to wait for a moment until the entry editor is shown.

**Comment by alvesmgabriel** [comment]
The latest snapshot worked fine on Windows OS (Windows 7 Professional, 64 bits) including the DOI search. However, in Ubuntu, the jabref is still freezing with any actions, for example to edit an entry with double click or by the icon menu and, after some minutes (3 ~ 5 min) I forced it to quit.

**Comment by janwcoenen** [comment]
It freezes long term. Beach ball off death on the mac. Only wait out is to kill it. 

--
Sent from my iPhone 
+491707775573

**Comment by jonasstein** [comment]
Works on gentoo Linux with 
```
JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131
```

**Comment by matthiasgeiger** [comment]
As there are other problems reported which cannot be really reproduced on Windows machines with an Oracle Java (JDK) installation - can you please tell us whether you are using an Oracle JDK or OpenJDK equivalent?

Thanks!

**Comment by alvesmgabriel** [comment]
I didn't mention, but I tested jabref (c0ca8507) on Windows 7 installed on a virtual machine and I used the jar file instead exe file.

```
Windows 7 Professional (64 bits) on Oracle VM VirtualBox (5.1.20)
Oracle JDK version (1.8.0_45-b15)
JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07.jar
```

@jonasstein, this is a good observation, however in my computer jabref (c0ca8507) still freezing. My kernel version is ``Linux 4.6.0-040600rc7-generic x86_64``.

**Comment by Siedlerchr** [comment]
The Oracle jdk version is very much outdated, you should update that first
For ubuntu/debian there is a 3rd party repo which provides actual Oracle
java version

Am 20.06.2017 2:37 nachm. schrieb "alvesmgabriel" <notifications@github.com

**Comment by alvesmgabriel** [comment]
In fact I tested the latest build on two machines, one with Linux and other with Windows. The both computers settings are:

**1) Ubuntu 16.04 LTS**
```
Linux 4.6.0-040600rc7-generic x86_64
Oracle JDK (1.8.0_131-b11)
JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07.jar
```

**2) Windows 7 Professional**
```
Windows 7, 64 bits, Service pack 1, running on Oracle VM VirtualBox
Oracle JDK (1.8.0_131-b11)
JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07.jar
```

I updated my Oracle JDK, in Windows, from `1.8.0_45-b15` to `1.8.0_131-b11`. I tested jabref in Windows, again, and it works fine. However in Ubuntu it still freezing. I will try to update the kernel.

Hope this helps.

**Comment by matthiasgeiger** [comment]
Thanks for your testing effort... Although we are still not able to nail down the actual reason for the freezing :-/

**Comment by janwcoenen** [comment]
Tried ow the latest Jar and this now started freezing as well …

Jan

**Comment by mvt91** [comment]
hello,

I have a similar problem under linux.
May I indicate it here ?
[Last message ](https://github.com/JabRef/jabref/issues/2722) - (Wrong thread, OSX)
Best regards

MVT

**Comment by koppor** [comment]
@mvt91: Which Linux version?

**Comment by mvt91** [comment]
Hello Koppor,

As mentioned in the "Last Message" : Linux Mint Cinnamon 18.1
I removed openJDK and all its components and installed Oracle Java.
Same problems.
I migrate Mint from 18.1 to 18.2 recently.
I didn't have a new try with JabRef and the last nightly (holidays).
I'll do it next week

**Comment by seb45tian** [comment]
Having the same problems on Ubuntu 14.04 LTS. I got the "Error while fetching from DOI. Invalid URL" message in 3.8. Tested the latest 4.0 dev-snapshot (2017-07-19--master--894799b2f) and jabref freezes after any action.

Ubuntu 14.04 LTS 3.13.0-32-generic
Java openJDK 1.8.0_111
JabRef-4.0-dev--snapshot--2017-07-19--master--894799b2f.jar

If wanted, I can send some verbose logs?

Would it be possible to release a fix for the DOI search for the 3.8 version as a temporary solution? I don't think the freezing of jabref in Linux is directly connected to the DOI search error.

**Comment by koppor** [comment]
@seb45tian We are investing our energy to get the 4.0 version out: https://github.com/JabRef/jabref/milestone/8

We are aware that backports to 3.8.2 are possible. However, this comes with follow-up maintenance costs, where we don't have resources for. @jonasstein also thought about releasing a fix for Gentoo linux, but there are unfortunately still issues with building JabRef on Gentoo.

What would help if someone could make a `git bisect` session at Ubuntu to identify the commit which causes the freeze. I know, this takes much time. But maybe, one can do something else in parallel.

**Comment by mvt91** [comment]
@koppor The problem is not only the DOI freeze. When you clic on an entry to see the details (tabbed view to see ordered information and bibtext entry format (last tab on the right) JabRef freezes too. But it works under W8.1
The information is in that [post](https://github.com/JabRef/jabref/issues/2722). I can duplicate it here if you want but I'm busy the next 5 days.
If I can help you, dont't hesitate but I don't know what is a git bisect.
I saved "old builds" under Mint. I'll check it next Monday. Sorry, I can't do it early

**Comment by LinusDietz** [comment]
There were many fixes since the reporting of these bugs, and I guess this problem is resolved now.

**Comment by mvt91** [comment]
Sorry for the delay.
Thanks.
I'll try new release.
