### ISSUE TITLE
JabRef freeze in opening entry editor

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#2963]
JabRef-4.0.0-dev--snapshot--2017-07-03--master--6897b10fb.jar on LInux Mint LMDE.

java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

Steps to reproduce:

1. create a new database
2. Menu BibTeX -> New entry...
3. Select an entry type (such as article)

JabRef does not do anything (processor idle) and cannot even be closed.

<details>
  <summary>Log File</summary>
$   java -jar ./bin/JabRef-4.0.0-dev--snapshot--2017-07-03--mast--6897b10fb.jar 
AI: INFO 04-07-2017 11:56, 19: Configuration file has been successfully found as resource
File: grouptree.fxml not found, attempting with camel case
Jul 04, 2017 11:56:48 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
File: grouptree.css not found, attempting with camel case
Jul 04, 2017 11:57:44 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66
Jul 04, 2017 11:57:45 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.66

</details>

**Comment by Siedlerchr** [comment]
Could you please try again with an updated JRE? The log indicates that your runtime version is older than the  version with which the javafx stuff was created
The current version is:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```

**Comment by ilippert** [comment]
JabRef 4.0.0-dev--snapshot--2017-07-03--master--6897b10fb
Linux 4.11.8-200.fc25.x86_64 amd64 
Java 1.8.0_131

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

I confirm the issue. Opening a database works. But double clicking an entry to open entry editor does not work and jabref freezes.

**Comment by Siedlerchr** [comment]
I am using Xubuntu 16.04 in a Virtual machine, and I can not reproduce this behaviour. Do you use openjdk or oracle jre?
It takes a moment to open the entry editor, yes, but I did not encounter a freeze

**Comment by Siedlerchr** [comment]
Hm, I just tested the steps above. On Xubuntu 16.04 (8GB ram) with oracle jdk I can not reproduce this behaviour. It takes a moment to open the entry editor, but I can not report a freeze.

**Comment by ilippert** [comment]
@Siedlerchr I believe I use oracle jdk, because openjdk would/should be indicated when prompting the shell for java -version.

**Comment by mlep** [comment]
After update of Java from Oracle:
> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

and using the last master (JabRef-4.0.0-dev--snapshot--2017-07-06--master--edd3f7cc1.jar),
I get the same behavior: a freeze (if it takes a "moment", this is a very long moment... (> 10 minutes))
JabRef is not responding (even for closing the window). I had to kill it.
Note: no CPU usage reported.

In the terminal, I get:
$ java -jar JabRef-4.0.0-dev--snapshot--2017-07-06--master--edd3f7cc1.jar 
AI: INFO 07-07-2017 10:15, 19: Configuration file has been successfully found as resource
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case

So, no more warnings regarding JavaFX.

And same behavior when using an existing database and double-clicking on an entry (in an attempt to edit this entry).

**Comment by lenhard** [comment]
I just tried this with the current master on Windows 7. Everything is working fine. Could this be a linux problem?

**Comment by mlep** [comment]
Could be. Any way to help in the diagnosis?
BTW, if this bug is postpone to v4.1, it means JabRef 4.0 will be not usable for Linux users...

**Comment by lenhard** [comment]
We have Linux users (@Siedlerchr) that do not experience this problem, so it's not a blocker for Linux per se.

**Comment by mlep** [comment]
Sorry, I overlooked this point.
What kind of test can be carried out to investigate the cause?

**Comment by lynyus** [comment]
We just talked about that in the devcall and are also unsure what the underlying problem is and which information can help us to solve this issue for everybody. :/

**Comment by lenhard** [comment]
To follow up on this: What we need is someone who experiences this error (no one in the dev team can reproduce it, no one uses Mint) to install the development environment and debug the failure.

So far there were two people using Linux Mint experiencing this, but no other OS (if I didn't overlook something). It might be something in the Mint environment.

**Comment by mlep** [comment]
Note: JabRef-4.0-dev--snapshot--2017-07-22--master--8730d02d9.jar does not freeze when using 
````
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
````
with 
````
 openjfx-8u60
````

**Comment by ilippert** [comment]
I had confirmed the issue, too, and I am running Fedora.

**Comment by matthiasgeiger** [comment]
Can you please check which `openjfx` version you are using? 
Thanks!

**Comment by mlep** [comment]
version 8.0.60

**Comment by lenhard** [comment]
@ilippert Good to know, thanks! Could you try out openjfx 8.0.60 and see if this solves the problem on your machine?

In #3038 we also have a Mint user who doesn't report that the entry editor crashes. So this is most definitely a javafx configuration problem on Linux that's not specific for a certain distro.

Can we just tell people to use the javafx version 8.0.60 if they experience this? I still see very little that we can do from the side of JabRef here.

**Comment by ilippert** [comment]
@lenhard Hmm, to be detailed:
I have now updated Java via http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html hopeing it includes openjfx 8.0.60. But, sorry, I am too much a lay person to know how I investigate, which version of openjfx I now have.

JabRef 4.0-dev--snapshot--2017-07-25--master--0847f5d15
Linux 4.11.11-300.fc26.x86_64 amd64 
Java 1.8.0_144

uname -a results in
Linux  4.11.11-300.fc26.x86_64 #1 SMP Mon Jul 17 16:32:11 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


With this configuration the error persists.

**Comment by matthiasgeiger** [comment]
@Siedlerchr fixed an issue yesterday that let JabRef freeze in another context - see #3058.

If you are using a configuration with automatic timestamp updated upon changing an entry the underlying problem might also be the cause of the freezes reported by you @mlep and @ilippert 

Could you please check, whether the problem persists with the latest master builds from https://builds.jabref.org/master ?

Thanks!

**Comment by mlep** [comment]
Works as expected with JabRef-4.0-dev--snapshot--2017-07-30--master--81e6e8ed6.jar
Great! Thanks!

**Comment by ilippert** [comment]
JabRef 4.0-dev--snapshot--2017-07-30--master--81e6e8ed6
Linux 4.11.11-300.fc26.x86_64 amd64 
Java 1.8.0_144

does not work as expected; still crashes.

**Comment by matthiasgeiger** [comment]
... too bad.

**Comment by Siedlerchr** [comment]
@ilippert  Could you please try to start JabRef from commandline and check if there is any exception or error printed?
e.g. java -jar JabRef.jar

**Comment by ilippert** [comment]
I did check, nothing gets printed in the shell after producing the freeze effect. I am happy to offer other traces - if you suggest which

**Comment by matthiasgeiger** [comment]
Okay, as the Problem is solved for @mlep now this might be related to some weird combination of different aspects.

Let's try to narrow the potential cause: Could you please export your preferences (Options -> Preferences -> Export in the lower left side of the Dialog) and then reset the preferences (same Dialog). Does the problem of freezing persist?

**Comment by ilippert** [comment]
thanks, the problem persists. This morning, I have even experienced a few java core dumps today. see https://pastebin.com/XkNReGKi 
The vague pattern I experience about the core dumps is as follows: if I just download the latest master and run it, JabRef starts and crashes after some time, sometimes even before the UI shows up; then when I try to start JabRef again via the shell, I get the feedback 
`Error: Invalid or corrupt jarfile JabRef--master--latest.jar`

Now, if I set the JabRef master jar as read only, the core dumps do not seem to happen.

Then I tested JabRef for the original issue, with no files opened, and preferences reset. I then created a new file, imported some entries; and once I attempt to open the entry editor, it crashes; and nothing is reported on the shell.

**Comment by Siedlerchr** [comment]
Regarding your java core dumps, I found this bug report with a potential solution:
https://bugs.openjdk.java.net/browse/JDK-8160933


As you say this only happens when you open the entry editor, I have the vague feeling that it could be related to the CSL citation style lib. but no idea how to fix this,


Could you try to compile and run it directly from source code?
E.g. do a `git clone https://github.com/JabRef/jabref.git`
Then cd into that directory JabRef and execute `./gradlew run` 
It will download all kind of libs, compile and then start.

**Comment by ilippert** [comment]
compiled and then started successfully. I am not registering anything in the shell when it crashes (crash reproduced).

**Comment by ilippert** [comment]
I have also now started without all my preferences. I have closed all files; and created a blank one. As soon as I create a new entry (that would be opened in the entry editor), JabRef breaks down.

I am happy to investigate further with your patient guidance

**Comment by koppor** [comment]
@ilippert We assume recent fedora with recent updates and OrcleJDK 1.8.131?

**Comment by ilippert** [comment]
thanks!
JabRef 4.0-dev--snapshot--2017-08-08--master--3acd1f8d0
Linux 4.11.11-300.fc26.x86_64 amd64 
Java 1.8.0_144

this java version is from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Fedora is up to date. 

hmm, how does OrcleJDK 1.8.131 relate to Java 1.8.0_144?

**Comment by koppor** [comment]
`git bisect` lead us to https://github.com/JabRef/jabref/commit/c9566c2

@ilippert Do you have a checkout? Can you confirm, that `./gradlew run` at commit c9566c2 ( `git checkout c9566c2`)  leads to a non-working JabRef, but `ea76246` works?

**Comment by ilippert** [comment]
hi, 
56577b5c58bcf10e3617e438cbadae5f99655be0 leads to crash when attempting to open the entry editor.

c9566c2a92d460c05282544cf12c9908163a2b93 allows me partially to use the editor; though it literally takes seconds for the entry editor to load. I can then work in the editor and close it with the entry editor close button (I can repeat this for many entries >10). However, when I simply click onto another entry in the entry table whilst having opened the entry editor (hoping to open the entry editor for that other entry), it normally crashes (with one exception in which it did not directly crash).


ea762466667c88972fa06f3517ce5c9b01761f7f allows me partially to use the editor: opening the editor is much much faster (within a one second range;  sometimes, however, JabRef directly crashes when trying to open the entry editor). I can then work in the editor and close it with the entry editor close button. Sometimes, it works then to open the entry editor for another entry (sometimes it crashes then; I achieved opening max 2 or 3 different entries in the entry editor). However, when I simply click onto another entry in the entry table whilst having opened the entry editor (hoping to open the entry editor for that other entry), it directly crashes.

Sorry, this is not a straightforward confirmation...

**Comment by ilippert** [comment]
"playing" with various checkouts...

beta works wonderfully, of course ;) that is: 0bbb9303f940b58ceaa0a35b0cc8b691057b6505

c3a898fc0978156a13a547d6f08c43510b925ea7, 3acd1f8d0ed798afd5fe810bcbd5e6c718b88a32, 3344c629c114349115354fbaa7b08da593b055 and 6c4e71c4b75830361960fd5041a3298f96386955 do not allow me to open entry editor.

ede4dc8ef3ffbcec2400557b8579c37330dd67d3, fcac52707c78d8a0f7ade8975c8b67b023f7f777, a9e20660e07992b7f5739ce53c9156ae45623abf work wonderfully.

b02433b34b8384be1b090fdf8301d187ba9701db gets me to a behaviour in which I can open the entry editor, but then it starts to crash, similar to the description in https://github.com/JabRef/jabref/issues/2963#issuecomment-321329189

4832e5d867d4d6e9b8bd438bdad9461dc6457602, 45435927242d8b1de50e6651e57697290e44f4e5 do not seem to have an entry editor ;)

78185153be818bed63b350b52a145d270d9b84dc does have the frame of the editor, but not fields; but no crashes ;)

**Comment by koppor** [comment]
Oh, wow, good to know.

Superficial question: Does `snap install jabref --edge --devmode` work at your side and does the snap JabRef work (Refs https://github.com/JabRef/jabref/pull/2345/)?

**Comment by ilippert** [comment]
works well, it seems to run faster than the other ways of running jabref.

I get a range of warnings, like 
     `WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.111
Aug 11, 2017 2:07:25 AM javafx.fxml.FXMLLoader$ValueElement processValue
`

as well as 

`(java:3766): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(java:3766): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
`

**Comment by Siedlerchr** [comment]
So apart from some GTK errors and the warnings, the snap works fine and does not crash?

**Comment by ilippert** [comment]
yes, indeed - it works fine at least with respect to this current issue of the entry editor; I did not check it with respect to other issues.

**Comment by Siedlerchr** [comment]
Okay, so I would close this for the moment.
