### ISSUE TITLE
Very small fonts in groups panel and entry editor on high dpi screen

### ISSUE THREAD

**Issue by juejung** [JabRef/jabref#3034]
JabRef version 4-beta2  on Ubuntu 17.04 with open JDK 1.8.0_131 on a high dpi screen
the scaling of the menu, table and icons looks good. However, the font size of the groups panel and the entry editor is really small and I don't see a way to increase it -- see attached screenshot.

![image](https://user-images.githubusercontent.com/1740639/28445503-ab810d46-6d92-11e7-8888-6776147d973b.png)
The preview font is also extremely small and non-readable.
![image](https://user-images.githubusercontent.com/1740639/28445771-82b32f5a-6d94-11e7-8b01-77965ca5fb00.png)

**Comment by Siedlerchr** [comment]
ideas for solution:
https://docs.oracle.com/javafx/2/text/jfxpub-text.htm
http://docs.oracle.com/javafx/2/css_tutorial/jfxpub-css_tutorial.htm

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Comment by juejung** [comment]
@tobiasdiez Thanks for the quick fix. Yes it fixes the font in the groups and the input table section but it does not fix the fonts in the preview section, see the two images below. The latter is not really a problem for me as I don't really use the preview section. I tested this on Windows 7 as well as Ubuntu 17.04.
![image](https://user-images.githubusercontent.com/1740639/29098270-8d37000a-7c6c-11e7-8511-013ee5de75de.png)
So this looks great now.
![image](https://user-images.githubusercontent.com/1740639/29098280-9e3114a4-7c6c-11e7-8cc5-646f00354238.png)

But the preview is still tiny and unreadable.

**Comment by Siedlerchr** [comment]
The Preview is another thing, are you using The CSL styles or the own JabRef style?
For the first one you can easily add the attribute font size to the entry preview:
`<font face="sans-serif" size = "26">`
The other one refs #2299

**Comment by juejung** [comment]
@tobiasdiez @Siedlerchr This works great thank you. I still found the remaining issues on hi dpi screens and they all concern sections in the preferences menu with 'table' entry fields. I posted the screenshots of the four occurrences that I found. The 'table' entry field is too small to fit the fonts properly. It all looks squeezed together.
![image](https://user-images.githubusercontent.com/1740639/29123001-442f8e74-7ce2-11e7-8331-e9dc68c2c096.png)
![image](https://user-images.githubusercontent.com/1740639/29123020-53562610-7ce2-11e7-9ed8-9e1051c5a279.png)
![image](https://user-images.githubusercontent.com/1740639/29123031-5aae0f0e-7ce2-11e7-871e-1dabd155b87a.png)
![image](https://user-images.githubusercontent.com/1740639/29123052-6b79056e-7ce2-11e7-84d5-8e3af7680ee6.png)

**Comment by khatchad** [comment]
According to the [above comment](https://github.com/JabRef/jabref/issues/3034#issuecomment-321251324), I believe that this issue should be open.

**Comment by sschuldenzucker** [comment]
Still having this issue with all text except for menu titles/items in 4.1.

**Comment by Siedlerchr** [comment]
Hi, we are currently reworking the whole application to javafx.
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See #3621 for further details.
