### ISSUE TITLE
Changes in Source Tab are not saved correctly without switching to another tab

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#3086]
JabRef version 4.0-beta2 on Debian 9 Stretch AMD64

Steps to reproduce:

1. Add a book entry
2. Add `title`, `author` etc. and save
3. Add `subtitle` and save
4. Switch to another entry
5. Return to the previous entry --> `subtitle` disappeared!!!!

It is very annoying and happens also with other fields.

**Comment by koppor** [comment]
Which java version? Did you try our latest build? You can also try `snap install jabref --edge --devmode`. - [snapd should be available at Debian testing](https://snapcraft.io/docs/core/install-debian).

**Comment by matthiasgeiger** [comment]
Hi @Doc73,
I cannot reproduce the problem on my machine with your description neither using the 4.0-beta2 nor using the most recent dev builds...

Can you please check whether this problem is also present in the dev builds available from https://builds.jabref.org/master ?

**Comment by Doc73** [comment]
Dear all,
I use latest `openjdk-jre` version available in Debian Stable repositories, i. e. 8u141-b15-1~deb9u1, with `openjfx` v. 8u111-b14-1.

I can reproduce it sistematically with beta2. Try this way:
1. Add a book with author, title, date, key
2. Search the item with a field common to other items, in order to have other items in table with the one just added.
3. In biblatex **source editor**, add `titleaddon`
4. In the table, switch with arrows to another item
5. Return to previous item

Later I'll try dev builds.

**Comment by Doc73** [comment]
I can confirm that the real issue is that every changes made directly into the source editor are not saved, even if you press the CTRL+S keys. :-(

**Comment by matthiasgeiger** [comment]
Thanks for the clarification.

I can now reproduce the problem in 4.0-beta2 and `master`: Changes in the source tab are not stored when switching to another entry. 
However, if you switch to another tab first before selecting another entry this problem does not happen. This might be a workaround for you.

Potentially related to #2946 resp. 03861a35028f162bf0034a143648641ca93aee7c - @tobiasdiez can you check whether this is easily solvable?

Best regards,
Matthias

**Comment by Doc73** [comment]
@matthiasgeiger
Yes, I noticed this workaround. 
BTW, thank you very much!

**Comment by Doc73** [comment]
@matthiasgeiger
Yes, I noticed this workaround. 
BTW, thank you very much!

**Comment by lenhard** [comment]
@Doc73 @matthiasgeiger I think I have fixed this. Can you please try out http://builds.jabref.org/fix-sourcetab-update/ and see if it works for you?

**Comment by Doc73** [comment]
@lenhard 
Many thanks! It seems working!

**Comment by wujastyk** [comment]
Problem: in editor, bibtex source tab not updating.

Steps:  
1. add article
2. go to optional fields, add DOI
3. fetch DOI data and accept "replace"
4. Fields all okay in Required tab
5. All fields blank in Bibtex source tab.


JabRef 4.0-dev--snapshot--2017-08-11--master--18fffc6b9
Linux 4.8.0-58-generic amd64 
Java 1.8.0_144

**Comment by matthiasgeiger** [comment]
@wujastyk This should also be fixed by the change of @lenhard I just merged into the master branch. 

Please try the newest version from https://builds.jabref.org/master. Thanks!

**Comment by wujastyk** [comment]
JabRef 4.0-dev--snapshot--2017-08-13--master--ce5038dd3
Linux 4.8.0-58-generic amd64
Java 1.8.0_144

Problem persists.  Exactly as previously described.  :-(

**Comment by lenhard** [comment]
@wujastyk I've tried with the same JabRef version, but on Win7, but I cannot reproduce your problem. Can you give a DOI? I do the following:
 1. add article 
 2. go to General fields tab, add DOI https://doi.org/10.1016/j.future.2017.01.006
 3. Click get BibTeX data from DOI
 4. Click replace
 5. All fields properly populated in the required tab and and in the BibTeX source tab

**Comment by wujastyk** [comment]
I do the same, but I enter the doi in the Optional Fields tab

**Comment by koppor** [comment]
@wujastyk Did you customize your entry types somehow? (http://help.jabref.org/en/CustomEntryTypes)

**Comment by matthiasgeiger** [comment]
I was able to reproduce the problem and I opened #3103 for this bug.

**Comment by wujastyk** [comment]
Yes.

Now offline for the rest of tge day, flying Vienna-Edmonton.

**Comment by matthiasgeiger** [comment]
Have a good flight!
Should now be fixed in recent master builds.

**Comment by wujastyk** [comment]
Yes, with

JabRef 4.0-dev--snapshot--2017-08-14--master--0b779cdc4
Linux 4.8.0-58-generic amd64
Java 1.8.0_144

this bug is fixed.  Thanks!

Dominik
