### ISSUE TITLE
Jabref docbook export: editor not properly exported

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3134]
Jabref3.8.2
Windows 7 6.1 amd64
Java 1.8.0_131
 
Steps to reproduce:

1. using this line on the console
java -jar C:\Programme\JabRef\JabRef-3.8.2.jar -o ch04BiB.xml,docbook -n true chapter04.bib
2. getting amongst chai4BiB.xml 
09:35:10.136 [AWT-EventQueue-0] WARN  net.sf.jabref.logic.exporter.ExportFormat - The following formatters could not be found: CreateDocBookEditors

The books with editors in that library are not well transformed:
A Formatter for the editor field is not found which would be analogous to the author field:
```
<editor><firstname></firstname><surname></surname></editor>
```
Furthermore, the offending entry is "incollection" in the Bib-library, however the xml export lists it as article.
From the official documentation DocBook 5_ The Definitive Guide - Norman Walsh.prc:

     Additional attributes: pubwork (enumeration) = “article” | “bbs” | “book” | “cdrom” | “chapter” | “dvd” |  emailmessage” | “gopher” | “journal” | “manuscript” | “newsposting” | “part” | “refentry” | “section” |  series” | “set” | “webpage” | “wiki” 

it looks that section would be appropriate. 
```
<biblioentry xreflabel="BD03" id="BD03">
   <authorgroup>
       <author><firstname>Robin P.</firstname><surname>Boushey</surname></author>
       <author><firstname>Daniel J.</firstname><surname>Drucker</surname></author> 
       [Formatter not found: CreateDocBookEditors] Larsen, P. Reed and Kronenberg, Henry M. and Melmed, Shlomo and Polonsky, Kenneth 
   </authorgroup>
   <citetitle pubwork="article">Gastrointestinal Hormones and Gut Endocrine Tumors</citetitle>
   <publisher>
      <publishername>Saunders&#44; Philadelphia PA</publishername>
   </publisher>
   <edition>10</edition> 
   <artpagenums>1777&#x2013;1796</artpagenums> 
   <pubdate>2003</pubdate>  

</biblioentry>
```
It is obviously an ommission.
Regards Bernhard

**Comment by lenhard** [comment]
@bernhard-kleine I think you've already reported this bug one month ago and we fixed it, see #3020

Above you're using 3.8.2. Could you please try again with a more version, e.g. the current master build http://builds.jabref.org/master/ and report back if it works?

**Comment by bernhard-kleine** [comment]
My fault: I am using a line from a text file not to compose it everytime I need it and forget to update that to a newer version. It works well with

```
java -jar C:\Programme\JabRe4\JabRef-4.0-beta3.jar -o ch04BiB.xml,docbook -n true chapter04.bib
```

**Comment by bernhard-kleine** [comment]
still the issue that incollection comes an article is still not settled and should be improved together with support for Docbook5

**Comment by bernhard-kleine** [comment]
When is this Hacktoberfest to take place?

**Comment by lenhard** [comment]
It is taking place right now: https://hacktoberfest.digitalocean.com/

The label is there to point people to this issue in the hope that someone implements a fix for it.

**Comment by bernhard-kleine** [comment]
As the hacktoberfest is some days old I may ask for an update. Is there any?

**Comment by lenhard** [comment]
Well, it does not seem that someone was interested in tackling this.

**Comment by bernhard-kleine** [comment]
How can a non-programmer like myself provide help with this issue?

**Comment by tobiasdiez** [comment]
The docbook export is implemented using a custom export layout. You can find the current version here: https://github.com/JabRef/jabref/blob/master/src/main/resources/resource/layout/docbook.layout
You can use this layout as a starting point and add the docbook 5 support yourself. No real programming knowledge is required, just a bit of time and a text editor. The syntax of export layouts and how to test/include them is described with a lot of detail in the [help](https://help.jabref.org/en/CustomExports).

**Comment by bernhard-kleine** [comment]
In part that seems simple enough, but the main worries about the missing <personname> in the macro \format[CreateDocBookAuthors] (same for editors)  remain. Where do I find it?

**Comment by bernhard-kleine** [comment]
the following is from the docbook5 guide. I have not tested the macro \entrytype but first of all I would like to know how to derive the abbrev: e.g. Kleine et al. (2016), or Kleine und Diez (2016), it looks like it is a macro. But I do not the name.
 
`<biblioentry xml:id="{\bibtexkey}">
	<abbrev/>
	<biblioset relation="{\entrytype}">
		<title/>
		<publisher>
			<publishername/>
		</publisher>
		<bibloid class="doi"/>
		<bibliomisc><link xref:link="\format[XMLChars]{\url}">\format[XMLChars]{\url}</link></bibliomisc>
	</biblioset>	
	<biblioset relation="article">
		<authorgroup>
			<author>
				<personname>
					<firstname/><surname/>
				</personname>
			</author>
		</authorgroup>
			
</biblioentry>`

**Comment by tobiasdiez** [comment]
Sorry, I don't really get your problem. The author's formatter is really powerful and described in detail in the [help](https://help.jabref.org/en/CustomExports#the-authors-formatter). But for some reason the docbook export needed a special format, so there is also [CreateDocBookAuthors](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/layout/format/CreateDocBookAuthors.java).
But this is "real" code that you can't easily change. If there is a problem in this formatter, just tell us and we can fix it directly.

**Comment by Siedlerchr** [comment]
As we recently worked on the improvement of the docbook5 export I guess this issue can be closed now

**Comment by bernhard-kleine** [comment]
The editor in the example is now correctly formatted.
