### ISSUE TITLE
Unexpected behaviour: Groups search - Item assignment

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#3176]
JabRef 4.0-dev--snapshot--2017-08-31--master--54e0994ba
Windows 10 10.0 amd64 
Java 1.8.0_141

Steps to reproduce:

1. Search for an group in your database using the new group search feature.
2. Select an item that is assigned to this group in the main table. The item is now marked in blue.
3. Search for another group in your database (your currently selected item should not belong to this group).
4. Select the other group you just searched for in the groups panel.
5. The item, that previously had been selected in the main table (as indicated by the blue colour and its appearance at the top of the main table items), is no longer selected/visible. Instead the items of the newly selected group are visible.

This behaviour is unexpected, as it does not allow you to quickly assign one item by using the groups search feature (i. e., search group -> select item -> search another group -> assign item to it). Instead you have to assign the group the "old-fashioned" way, i. e. either by drag'n'dropping it to the group of interest OR by using the menu associated with the group OR using both the item and the group search feature.
Just using the groups search feature alone won't do the trick, currently.

**Comment by Andrew-Lev** [comment]
I took a quick look at this, but am not sure what you're referring to.  Do you mean the 'groups interface' and the 'filter groups' feature that's located on the bottom of that pane?

**Comment by AEgit** [comment]
Yes, indeed:
"groups panel" = groups interface
"group search" = filter groups

**Comment by Andrew-Lev** [comment]
I tried it out by your steps, but dont see that same issue.  When I filter and select another group I still see my previous selection and can add it to that group.  I did find a defect while looking at this though, when you rename a group through the edit group option it doesnt get renamed in the group editor, only in the actual items that belong to that group.

**Comment by AEgit** [comment]
I've tried it again with:
JabRef 4.0-dev--snapshot--2017-09-02--entry-editor-performance--548537f12
Windows 10 10.0 amd64 
Java 1.8.0_141

I can confirm your observation, that the originally selected item is still selected (indicated in blue). The problem, however, is, that this item is not found at the top of the non-group items (displayed in gray), but is found somewhere hidden among other non-group items. This is not a major problem, if you only have a small database, but mine contains several thousand items. Therefore it gets very difficult to find again the item you initially selected (this is also the reason, why I initially thought that the selection had been lost).

**Comment by AEgit** [comment]
This issue persists in:

JabRef 5.0-dev--snapshot--2018-10-28--master--05047f32a
Windows 10 10.0 amd64 
Java 1.8.0_191

This issue is potentially connected to the fact that currently non-group items are not shown in the main table (not even in gray; see https://github.com/JabRef/jabref/issues/4237).

**Comment by AEgit** [comment]
See also the comment here:
https://github.com/JabRef/jabref/issues/3436#issuecomment-375779146

**Comment by sauliusg** [comment]
I can confirm the same behaviour in:
JabRef commit db96f88 (master)
Ubuntu-16.04
Java openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-116.04.1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-116.04.1, mixed mode, sharing)

**Comment by AEgit** [comment]
JabRef 5.3--2021-01-04--10180ed
Windows 10 10.0 amd64 
Java 14.0.2

The issues as described in https://github.com/JabRef/jabref/issues/3176#issue-254365305 (with the updates from https://github.com/JabRef/jabref/issues/3176#issuecomment-327133037) persist in the current developer version of JabRef.

**Comment by AEgit** [comment]
JabRef 5.4--2021-12-10--eff8073
Windows 10 10.0 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

This issue reported in in https://github.com/JabRef/jabref/issues/3176#issue-254365305 (with the updates from https://github.com/JabRef/jabref/issues/3176#issuecomment-327133037) persist in the current dev version. Please reopen!

**Comment by Siedlerchr** [comment]
Thanks to @LIM0000  this issue is now resolved in the latest development version.


We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment]
JabRef 5.7--2022-05-30--3222878
Windows 10 10.0 amd64 
Java 18.0.1 
JavaFX *unknown*

I am afraid, this issue persists in the current development version as far as I can tell. Note also, that it is currently difficult to verify the persistence of the issue, since the floating mode has been lost in the new versions of JabRef (though people are working to get it back: https://github.com/JabRef/jabref/pull/8206#issuecomment-960172096). However, since the selected item is even invisible when the "All Entries" group is selected, I reckon this problem persists as described in https://github.com/JabRef/jabref/issues/3176#issuecomment-327133037

**Comment by AEgit** [comment]
JabRef 5.11--2023-10-17--8ede31a
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20.0.2+3

I am afraid, this issue persists in the current development version as far as I can tell. Note also, that it is currently difficult to verify the persistence of the issue, since the floating mode has been lost in the new versions of JabRef (though people are working to get it back: https://github.com/JabRef/jabref/pull/8206#issuecomment-960172096). However, since the selected item is even invisible when the "All Entries" group is selected, I reckon this problem persists as described in https://github.com/JabRef/jabref/issues/3176#issue-254365305 with updates from https://github.com/JabRef/jabref/issues/3176#issuecomment-327133037

@koppor Can you please re-open this issue?

**Comment by Siedlerchr** [comment]
On mac this still looks fine and works as expected:
1. Select All entries group
2. Select the desired entries
3. Right click on the subgroup  -> entries are assigned to the group and stay selected 

Selected entries stay selected while I right click on the group
<img width="1505" alt="grafik" src="https://github.com/JabRef/jabref/assets/320228/235f3cb9-d5b0-4e53-bd63-5da83bd44577">

**Comment by AEgit** [comment]
Try with a large database with thousands of entries and groups the following:

Steps to reproduce:

    Search for an group in your database using the new group search feature.
    Select an item that is assigned to this group in the main table. The item is now marked in blue.
    Search for another group in your database (your currently selected item should not belong to this group).
    Select the other group you just searched for in the groups panel.
    The item, that previously had been selected in the main table (as indicated by the blue colour and its appearance at the top of the main table items), is no longer visible. Instead the items of the newly selected group are visible.

As mentioned in https://github.com/JabRef/jabref/issues/3176#issuecomment-327133037 the originally selected item is (probably? - I cannot see this in my large database atm) still selected (indicated in blue). The problem, however, is, that this item is not found at the top of the non-group items, but is found somewhere hidden among other non-group items. This is not a major problem, if you only have a small database, but mine contains several thousand items. Therefore it gets very difficult to find again the item you initially selected.

**Comment by Siedlerchr** [comment]
Ah now I better understand your problem. Yes, it's a bit cumbersome. But once the item is selected (no matter where, it stays selected) and you filter or select a group it will be added

**Comment by AEgit** [comment]
I am adding here a video to showcase the problem. Note, how the selected item turns "invisible" once the new group is being filtered for. This makes it impossible to drag'n'drop your selected item to another group, which obviously would be something you definitely would like to be able to do with the nice group filtering option.

https://github.com/JabRef/jabref/assets/12767489/6e88757b-30b8-429f-9a24-5af110b9d736

Given that the issue description as it stands now slightly differs from the original one. Should I open a new bug report in regards or should we re-open this one?

**Comment by LoayGhreeb** [comment]
@AEgit, can you check if this issue is fixed by https://github.com/JabRef/jabref/pull/11510?
