### ISSUE TITLE
Autocompletion gets in the way

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#3522]
If i want to edit the text e.g., inside the title field of an entry and jump to the front via Pos1 key or so autocompletion totally screws up the navigation, even if I am inside the text.
For me this is totally unnerving. The way the autocompletion works right now is not a lot better than it was before we disabled the old one...

**Comment by stefan-kolb** [comment]
@JabRef/developers As a fix I suggest to disable auto completion again by default.

**Comment by koppor** [comment]
Huge step: Survey in the forum. Who uses autocompletion, how, ...

Present edge cases, present solutions

Currently no resources for that, so we disable the auto completion.

**Comment by tobiasdiez** [comment]
What about adding a telemetry data point that tracks if user have autocompletion enabled or not?

**Comment by lenhard** [comment]
This has already been fixed with #3569, hence I am closing.

**Comment by tobiasdiez** [comment]
@lenhard As much as I like closed issues, I think this one should stay open. The underlying problem is still not fixed and we only disabled the autocompletion feature by default....in the long term, I would really like to have a functional autocompletion that we are proud to present to the user.

**Comment by stefan-kolb** [comment]
This issue doe not point to concrete problems tho. I think there are plenty of such issues open. This was just a general issue.

**Comment by tobiasdiez** [comment]
Ok, if you think that the issues https://github.com/JabRef/jabref/labels/autocompletion are enough, then we can of course leave this closed (as I said, I love closed issues 😄 ).

**Comment by stefan-kolb** [comment]
Dunno, maybe we could use an issue where all problems are collected, if someone wants to give the AC a try again.
