### ISSUE TITLE
Does not find textfiles

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#3687]
```
JabRef 4.2-dev--snapshot--2018-01-31--maintable-beta--be9be8f0a
Linux 4.13.0-32-generic amd64 
Java 1.8.0_161
```
I used this version due to Bug #3641

Steps to reproduce:

1. Open the bibfile below in JabRef on Linux
2. Leftclick on the file-icon
3. assert that any text-file "Crick_Klug_1975_Nature.ocr" exists (add it again to JabRef to be shure that it is in the right folder)
4. choose this "Crick_Klug_1975_Nature.ocr"-text-file
5. You get a warining that this file does not exist

![screenshot from 2018-02-02 11-40-11](https://user-images.githubusercontent.com/15687581/35729331-8e34b62c-080e-11e8-8b18-6570163a98d8.png)

[example.bib.txt](https://github.com/JabRef/jabref/files/1638862/example.bib.txt)

```bib
% Encoding: UTF-8
@Article{crick1975kinky,
  author   = {Crick, F.~H.~C and Klug, A},
  title    = {Kinky helix},
  journal  = {Nature},
  year     = {1975},
  volume   = {255},
  number   = {5509},
  pages    = {530--533},
  month    = jun,
  adsnote  = {Provided by the SAO/NASA Astrophysics Data System},
  adsurl   = {http://adsabs.harvard.edu/abs/1975Natur.255..530C },
  doi      = {10.1038/255530a0},
  file     = {:PhDJK\\Literature\\DNA\\Weitere\\Crick_Klug_1975_Nature.pdf:PDF;:PhDJK\\Literature\\DNA\\Weitere\\Crick_Klug_1975_Nature.ocr:Text},
  groups   = {DNA},
  keywords = {rank2},
}
```

![screenshot from 2018-02-02 11-40-16](https://user-images.githubusercontent.com/15687581/35729492-25a9cbdc-080f-11e8-9b00-c5ded7d93cee.png)

<details>
  <summary>Log from Jabref  </summary>
```log
Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib
Opening: /home/jkalliau/ownCloud/LaTeXBI/LaTeX-Vorlage-Dissertation-TUWBI-201801/Literatur.bib
Warning: could not get message translation for "Opens JabRef's Twitter page" for locale de
```
</details>
<details>
  <summary>Log from terminal:  </summary>
```log
AI: INFO 02-02-2018 11:39, 20: Configuration file has been successfully found as resource
11:39:01.462 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib
11:39:01.733 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/LaTeXBI/LaTeX-Vorlage-Dissertation-TUWBI-201801/Literatur.bib
11:39:02.065 [AWT-EventQueue-0] WARN  org.jabref.logic.l10n.Localization - Warning: could not get message translation for "Opens JabRef's Twitter page" for locale de
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1File: errorconsole.fxml not found, attempting with camel case
File: errorconsole.css not found, attempting with camel case
```
</details>
<details>
  <summary>log from terminal on the first apperance:  </summary>
```log

** (java:21003): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
AI: INFO 02-02-2018 11:31, 20: Configuration file has been successfully found as resource
11:31:28.783 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib
11:31:29.026 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/LaTeXBI/LaTeX-Vorlage-Dissertation-TUWBI-201801/Literatur.bib
11:31:29.352 [AWT-EventQueue-0] WARN  org.jabref.logic.l10n.Localization - Warning: could not get message translation for "Opens JabRef's Twitter page" for locale de
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case
ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version 4.7.1ANTLR Runtime version 4.5.3 used for parser compilation does not match the current runtime version 4.7.1File: fileannotationtab.fxml not found, attempting with camel case
11:33:50.468 [JavaFX Application Thread] ERROR org.jabref.gui.DefaultInjector - Cannot instantiate dependency: interface org.jabref.model.util.FileUpdateMonitor
java.lang.InstantiationException: org.jabref.model.util.FileUpdateMonitor
	at java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_161]
	at org.jabref.gui.DefaultInjector.createDependency(DefaultInjector.java:43) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.instantiateModelOrService(Injector.java:114) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:147) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:132) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Injector.java:125) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.registerExistingAndInject(Injector.java:105) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.instantiatePresenter(Injector.java:57) ~[JabRef--maintable-beta--latest.jar:?]
	at org.jabref.gui.DefaultInjector.instantiatePresenter(DefaultInjector.java:58) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.views.FXMLView.lambda$loadSynchronously$1(FXMLView.java:96) ~[JabRef--maintable-beta--latest.jar:?]
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:929) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.views.FXMLView.initializeFXMLLoader(FXMLView.java:125) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.views.FXMLView.getView(FXMLView.java:137) ~[JabRef--maintable-beta--latest.jar:?]
	at org.jabref.gui.AbstractView.getView(AbstractView.java:28) ~[JabRef--maintable-beta--latest.jar:?]
	at org.jabref.gui.entryeditor.fileannotationtab.FileAnnotationTab.bindToEntry(FileAnnotationTab.java:29) ~[JabRef--maintable-beta--latest.jar:?]
	at org.jabref.gui.entryeditor.EntryEditorTab.lambda$notifyAboutFocus$0(EntryEditorTab.java:36) ~[JabRef--maintable-beta--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodException: org.jabref.model.util.FileUpdateMonitor.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_161]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_161]
	... 30 more
11:33:50.481 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IllegalStateException: Cannot load org.jabref.gui.entryeditor.fileannotationtab.fileannotationtab
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:101) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.views.FXMLView.initializeFXMLLoader(FXMLView.java:125) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.views.FXMLView.getView(FXMLView.java:137) ~[JabRef--maintable-beta--latest.jar:?]
	at org.jabref.gui.AbstractView.getView(AbstractView.java:28) ~[JabRef--maintable-beta--latest.jar:?]
	at org.jabref.gui.entryeditor.fileannotationtab.FileAnnotationTab.bindToEntry(FileAnnotationTab.java:29) ~[JabRef--maintable-beta--latest.jar:?]
	at org.jabref.gui.entryeditor.EntryEditorTab.lambda$notifyAboutFocus$0(EntryEditorTab.java:36) ~[JabRef--maintable-beta--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_161]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: javafx.fxml.LoadException: 
file:/home/jkalliau/prgm/JabRef/JabRef--maintable-beta--latest.jar!/org/jabref/gui/entryeditor/fileannotationtab/FileAnnotationTab.fxml:21

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2579) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef--maintable-beta--latest.jar:?]
	... 12 more
Caused by: java.lang.NullPointerException
	at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:131) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Injector.java:125) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.instantiateModelOrService(Injector.java:114) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:147) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.injectMembers(Injector.java:132) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Injector.java:125) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.registerExistingAndInject(Injector.java:105) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.injection.Injector.instantiatePresenter(Injector.java:57) ~[JabRef--maintable-beta--latest.jar:?]
	at org.jabref.gui.DefaultInjector.instantiatePresenter(DefaultInjector.java:58) ~[JabRef--maintable-beta--latest.jar:?]
	at com.airhacks.afterburner.views.FXMLView.lambda$loadSynchronously$1(FXMLView.java:96) ~[JabRef--maintable-beta--latest.jar:?]
	at javafx.fxml.FXMLLoader$ValueElement.processAttribute(FXMLLoader.java:929) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(FXMLLoader.java:971) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$Element.processStartElement(FXMLLoader.java:220) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:744) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441) ~[jfxrt.jar:?]
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409) ~[jfxrt.jar:?]
	at com.airhacks.afterburner.views.FXMLView.loadSynchronously(FXMLView.java:99) ~[JabRef--maintable-beta--latest.jar:?]
	... 12 more
```
</details>

**Comment by Siedlerchr** [comment]
Refs #3684

**Comment by Siedlerchr** [comment]
Sorry, I mean #3682 (on mobile I can't edit my comment)

**Comment by Siedlerchr** [comment]
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See #3621 for further details.

**Comment by JoKalliauer** [comment]
```
JabRef 4.2-dev--snapshot--2018-02-03--maintable-beta--7fb331130
Linux 4.13.0-32-generic amd64 
Java 1.8.0_161
```
Still the same message:
![screenshot from 2018-02-05 11-23-03](https://user-images.githubusercontent.com/15687581/35799740-fda267d4-0a66-11e8-8c32-8c40e64ceb09.png)

I just readded the file (over the filemenu), but sill does not work. (So the file should really exists at this place)

I found the problem I have to change the file-extension to .txt that it opened correctly

<details>
<summary>Terminalmessenges (bit different to before)</summary>
AI: INFO 05-02-2018 11:20, 20: Configuration file has been successfully found as resource<br/>
11:20:03.067 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib<br/>
11:20:03.299 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/LaTeXBI/LaTeX-Vorlage-Dissertation-TUWBI-201801/Literatur.bib<br/>
11:20:03.304 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/Kalliauer.bib<br/>
11:20:03.566 [AWT-EventQueue-0] WARN  org.jabref.logic.l10n.Localization - Warning: could not get message translation for "Opens JabRef's Twitter page" for locale de<br/>
File: grouptree.fxml not found, attempting with camel case<br/>
File: grouptree.css not found, attempting with camel case<br/>
File: aboutdialog.fxml not found, attempting with camel case<br/>
File: aboutdialog.css not found, attempting with camel case<br/>
File: errorconsole.fxml not found, attempting with camel case<br/>
File: errorconsole.css not found, attempting with camel case<br/>
</details>

**Comment by Siedlerchr** [comment]
You have to define the file type ocr as custom file type of mime type text.
I think there is an option in the tools menu, if I'm not mistaken

**Comment by tobiasdiez** [comment]
Shouldn't JabRef not gracefully handle such situations (open file using default program as specified by OS) or at least display a proper error message (could not find a program to open the file)? Vote to reopen.

**Comment by JoKalliauer** [comment]
@Siedlerchr 
Which option is it? I could not find it.

![screenshot from 2018-02-06 18-13-11](https://user-images.githubusercontent.com/15687581/35873328-ab26d694-0b69-11e8-8351-e65510226d63.png)

But anyway changing it to *.txt is a workaround which is perfect for me, but as @tobiasdiez said, it would be great if open would open it with the default program, or at least give an adequate error message.

**Comment by Siedlerchr** [comment]
@JoKalliauer  Tools -> Manage External File Types  -> Click on plus and you could define ocr as file type and extension with mimetype text/plain, but stil the file dialog should not tell file not foudn

**Comment by JoKalliauer** [comment]
@Siedlerchr 
It seems I'm still to silly. I changed to "English", but I still can't find "Manage External File Types".

Is the dropdownmenu shown below the correct one?

![screenshot from 2018-02-06 20-46-39](https://user-images.githubusercontent.com/15687581/35880882-5f55133c-0b7f-11e8-8a33-cd53f2023832.png)

**Comment by Siedlerchr** [comment]
Sorry my fault 🤦‍♂️ It's of course under Options! (one menu item to the right)

**Comment by JoKalliauer** [comment]
@Siedlerchr 
Thanks, also this solution works. 👍  (I thought I checked already every menu.)
Therefore "wait-for-feedback"-label can be removed, if you want to reopen it is up to you (the developers), or maybe start a new Issue.

![screenshot from 2018-02-07 09-23-17](https://user-images.githubusercontent.com/15687581/35905905-125318d0-0be9-11e8-8cb8-3507157772fe.png)

-It isn't possible to change the icon?
-Is there a way to add two extensions for the same entry?
