### ISSUE TITLE
Search box erroneously duplicates entered query strings

### ISSUE THREAD

**Issue by Sethur** [JabRef/jabref#3921]
I have indeed tested the latest master version from http://builds.jabref.org/master/ and the problem persists.

Version: Jabref 4.1 on Windows 7 on Java x64 Version 8 Update 162

Steps to reproduce:

1. Use large datebase (>1800 entries) with almost every entry having an associated PDF
2. Type something like "author = M"
3. Randomly observe that the searchbox will suddenly show "author=Mauthor=M". This does not happen every time, but on our system it takes about 
![image](https://user-images.githubusercontent.com/2142589/38296490-c33ba890-37f1-11e8-88a4-dc92e4648979.png)
4. The search will be largely broken afterwards

The only way to fix this is restarting Jabref.

**Comment by stefan-kolb** [comment]
Do you have autocompletion enabled?

**Comment by Sethur** [comment]
So I just checked again, it makes no difference whether auto-completion is enabled or not.

**Comment by Siedlerchr** [comment]
can you start JabRef from the command line (java -jar JabRef.jar)  and see a log entry then on the console when the freeze/errornouzs behaviour happens?

I can report similiar behaviour for the date field, when you try to enter a date like 2012-10-02

**Comment by stefan-kolb** [comment]
Duplicate of #3866

**Comment by Siedlerchr** [comment]
I think  this is related that the search is executed everytime the text changes:
`        EasyBind.subscribe(searchField.textProperty(), searchText -> performSearch());`

**Comment by Siedlerchr** [comment]
I recently added a delay before the search is executed, so I think this issue is solved

Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by wilthan** [comment]
Problem persists!
Three days ago I installed the snapshot master (JabRef_windows-x64_4_2-dev--snapshot--2018-04-13--master) and started to use it on a daily base. The first two days the search worked fine, that changed today.
My database has 12700 entries with more than half of them having pdf's attached.
I copied a search key into the search box and it immediately appeared twice. This does not happen every time and I have not found a way to reproduce the issue but looking for it while I work with JabRef.

**Comment by Sethur** [comment]
Problem persists with latest dev snapshot: 4.3-dev--snapshot--2018-04-26--master--7629b3171.jar. Interestingly, once a test is doubled, you can mark it with SHIFT POS1 which will "repair" the doubled string, i.e. it will then show only what you typed again.

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.
