### ISSUE TITLE
Integrity check should not list "abbreviation detected"

### ISSUE THREAD

**Issue by Sethur** [JabRef/jabref#3925]
Issue persists in latest dev master.

JabRef version 4.1 on Windows 7

Steps to reproduce:

1. Perform integrity check on database with abbreviated (MEDLINE or ISO) journal entries
2. There will be a warning for every abbreviated journal entry found

This should not be listed as an integrity problem since the current way JabRef handles common journal abbreviations is exactly by replacing the entire string in the Bib(La)Tex entry with the abbreviated one, so this behavior is expected.

Suggested solution: Scratch the integrity warning and replace the yellow warning icon when editing such entries with an info icon.

**Comment by Luv2C0de** [comment]
Hello if this is up for grabs I would like to tackle it. Is there any more documentation on the issue that I can familiarize myself with?

**Comment by Siedlerchr** [comment]
Hi,
thanks for your willingness to contribute1

**Comment by Siedlerchr** [comment]
Hi, thanks for your interest!
You can have a look here to set up your workspace and the general workflow:
https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md

**Comment by laolux** [comment]
An additional issue which could be tackled in the same fix are journals where name and abbreviation are the same. For example the journal "Science" as abbreviated "Science" and therefore always gets listed as a problem during integrity check.

**Comment by dschrempf** [comment]
Since I just wanted to file an issue, but found this one here: Has there been any progress made on this issue?

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by THgithub19** [comment]
Science still gets a yellow warning mark in Jabref 5.1, issue not resolved.

**Comment by koobs** [comment]
Confirming issue on latest master

```
JabRef 5.2--2020-12-14--e9be339
Windows 10 10.0 amd64 
Java 14.0.2
```
For the following `journaltitle`s: Wear, Chemosphere, Energy Procedia, Aquaculture, Zebrafish

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by koobs** [comment]
@tobiasdiez #6502 may be a dupe of this issue and/or #7208 may resolve it.

**Comment by koobs** [comment]
@tobiasdiez Confirming resolution (see screenshot) on:

```
JabRef 5.2--2020-12-20--84c8504
Windows 10 10.0 amd64 
Java 14.0.2
```

![2020-12-22 11_38_17-Integrity check should not list _abbreviation detected_ · Issue #3925 · JabRef_j](https://user-images.githubusercontent.com/1011612/102835243-15af0080-43ee-11eb-88ca-01579a257faa.png)
