### ISSUE TITLE
Problems finding fulltext for IEEExplore

### ISSUE THREAD

**Issue by krishnakumarg1984** [JabRef/jabref#3966]
Issues with IEEE full-text importer.

I have tested the latest master version from http://builds.jabref.org/master/JabRef--master--latest.jar on Windows 7 and the following problem is encountered.

JabRef version 4.2-dev on Windows 7 Enterprise (build 7601 service pack:1)

Steps to reproduce:

1. Use Jabref on a network with full-text access to IEEExplore articles (such as a university's network)
2. Start a new library with the following bibtex entry

```
@inproceedings{Morabito2017,
author = {Morabito, Bruno and Klein, Reinhardt and Findeisen, Rolf},
booktitle = {2017 American Control Conference (ACC)},
doi = {10.23919/ACC.2017.7963481},
isbn = {978-1-5090-5992-8},
month = {may},
pages = {3457--3462},
publisher = {IEEE},
title = {{Real time feasibility and performance of moving horizon estimation for Li-ion batteries based on first principles electrochemical models}},
url = {http://ieeexplore.ieee.org/document/7963481/},
year = {2017}
}
```

3.  Select this reference entry within Jabref and hit ```Alt``` + ```F7``` or go to ```Quality -> Look up full text documents```
4. After a while, the following pop-up dialog box opens
```No full text document found for entry Morabito2017```
5. Expected behavior: Navigate to this same ```URL http://ieeexplore.ieee.org/document/7963481/```.  This works perfectly fine and full-text PDF can be manually downloaded.  The auto downloader should have obtained this PDF and linked it to the citation entry.

**Comment by stefan-kolb** [comment]
The test for open access articles such as https://ieeexplore.ieee.org/document/7421926/ work.
There should be no difference for the other articles as long as you really have access.
It is hard to debug for me as I don't have IEEE access at university. @JabRef/developers Anyone of you has access?

**Comment by Siedlerchr** [comment]
I can reproduce this error. For me the IEEE fetcher tests fail when I am connected using university VPN.
The html page  I get from the URL Downloader talks about missing cookie support. I will see if I can fix that

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Comment by krishnakumarg1984** [comment]
No.... Please read the text very carefully...I have explicitly mentioned that I am using the latest developmental version. The problem still persists. Please reopen this issue

**Comment by stefan-kolb** [comment]
We just merged a pull request fixing it.

**Comment by Siedlerchr** [comment]
@krishnakumarg1984  Yes. I know. But I just merged the code into the master branch. The development build gets automatically updated and built by our CI servers whenever someone commits to the master branch. This usually takes a couple of minutes. 
The version string contains the first part of the commit id.  (help-> About)

**Comment by krishnakumarg1984** [comment]
Ah. I am so sorry for not correctly interpreting what you said. I shall try the latest development build and report back. Sorry for the mild confusion in my last post

**Comment by krishnakumarg1984** [comment]
@Siedlerchr  @stefan-kolb We may have to reopen this issue.

I just tried with the latest build

>
JabRef 4.2-dev--snapshot--2018-04-20--master--8bbc40e13
Windows 7 6.1 x86 
Java 1.8.0_161

from my university's network and same error pop-up message persists.  

I wonder why #3968 says only when in VPN? I am physically on the campus, with a machine in the library hard-wired to a LAN port.  Just to confirm that this is indeed a bug, there is no issue with full-text access from a standard browser pointed to http://ieeexplore.ieee.org/document/7963481/

**Comment by tobiasdiez** [comment]
I think @krishnakumarg1984 is right and the issue still persist. Just looking at the code,
https://github.com/JabRef/jabref/blob/8bbc40e13e016f7a28486179855be9a7c28b2adc/src/main/java/org/jabref/logic/importer/fetcher/IEEE.java#L38-L47
with
https://github.com/JabRef/jabref/blob/8bbc40e13e016f7a28486179855be9a7c28b2adc/src/main/java/org/jabref/logic/importer/fetcher/IEEE.java#L27
is never going to match `http://ieeexplore.ieee.org/document/7963481/`.

**Comment by Siedlerchr** [comment]
Hmm that's odd. I will look into that again tomorrow

**Comment by Siedlerchr** [comment]
@krishnakumarg1984  I just merged the fix which supports those the IEEE document urls you have like in your entry.  And I also tested your entry with university access and worked for me. So I would like you to test this again

**Comment by krishnakumarg1984** [comment]
@Siedlerchr  thank you. I shall go to university to check this out. Will report back the outcome

**Comment by krishnakumarg1984** [comment]
Woohoo.... You guys are amazing. I can confirm that this works from my university's network. Was able to download the full-text of the bibtex entry for which the issue was opened. 

Thank you for accepting and pro-actively working on this issue
