### ISSUE TITLE
"Find unlinked files" freezes when using for PDF

### ISSUE THREAD

**Issue by Bananach** [JabRef/jabref#410]
Using "Find unlinked files" does not work. 
Scanning the directory works fine, but when I press "Apply" it displays "Importing into Database..." without ever making progress.

The problem occurs only for PDFs. It is independent of filename and directory. It is also independent of file content, i.e. it even occurs for empty PDFs.

I am using Windows 7 and the problem occurs for both JabRef 2.11.1 and JabRef 3.0

**Comment by simonharrer** [comment]
Thank you for opening the issue. We are open for pull requests fixing this bug.

**Comment by Bananach** [comment]
I don't know what that means, but I assume I have to wait for the next release?

**Comment by stefan-kolb** [comment]
@Bananach We are working on it.

**Comment by stefan-kolb** [comment]
@Bananach should be fixed in current master.

**Comment by simonharrer** [comment]
Confirmed. I can reproduce something when I click on apply and then close the window which is openend after clicking on apply - which makes JabRef unusable.

**Comment by koppor** [comment]
Refs #507

**Comment by stefan-kolb** [comment]
@Bananach You can try the latest build at http://builds.jabref.org/master/. This issue should be fixed there.

**Comment by andrewufrank** [comment]
i have used the newest build http://builds.jabref.org/master/JabRef-3.8.2-dev--snapshot--2017-01-16--master--9e48a5ff8.jar and use debian stretch with Java (oracle tested: 
ou have the recommended Java installed (Version 8 Update 111

the find unlinked works for the first file, sometimes even for the second (if the window is closed in between) fails later. it fails immediately if more than one file is selected from the unlinked files. 
the feature would be a great help - please fix it!
thank you!

**Comment by tobiasdiez** [comment]
I can confirm that the bug is still there in the latest dev version. I will have a look.

**Comment by stefan-kolb** [comment]
See  #2309
