### ISSUE TITLE
Freezes when "Add to Group"

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#4197]
JabRef 5.0-dev--snapshot--2018-07-12--master--dd9b22911
Linux 4.15.0-24-generic amd64 
Java 1.8.0_171

Steps to reproduce:

1. open any bib-file (f.e. [input_4196_4197.bib](https://github.com/JabRef/jabref/files/2189259/input4196.bib.txt) )
2. Rightclick on any entry and choose "Add  to Group"
3. JabRef freezes ![screenshot from 2018-07-13 09-01-48](https://user-images.githubusercontent.com/15687581/42677510-42dae47a-867c-11e8-9389-930df5e99155.png)

<details>
<summary>Terminal</summary>

```cmd
jkalliau@jkalliau-Z87M-D3H:~$ java -jar /home/jkalliau/prgm/JabRef/JabRef--master--latest.jar
08:59:05.436 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib
08:59:06.432 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/Desktop/input.bib
08:59:14.184 [JabRef CachedThreadPool] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/Desktop/input4196.bib
08:59:17.623 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview

```
</details>

**Comment by bernhard-kleine** [comment]
I cannot confirm the behaviour, I have just added a new entry to a group, same Jabref version.

**Comment by JoKalliauer** [comment]
@bernhard-kleine : It might be related to https://github.com/JabRef/jabref/issues/3301#issuecomment-336533305:
```
You could try to change the Look and Feel. Other users reported problems with GTK L&F
```

**Comment by mlep** [comment]
I can confirm the behavior.
I thought it could be related to the LookAndFeel too, but I could not find how to change it (in JabRef 4.3.1, it was in Option -> Preferences -> Appearance).


JabRef 5.0-dev--snapshot--2018-07-12--master--dd9b22911
Linux 3.11-2-amd64 amd64 
Java 1.8.0_172

**Comment by JoKalliauer** [comment]
@mlep : Sorry for writing unclearly
@stefan-kolb reported in https://github.com/JabRef/jabref/issues/4190#issue-340621637 
``` appearance tab inside preferences is empty``` 
![screenshot from 2018-07-13 09-38-14](https://user-images.githubusercontent.com/15687581/42679056-0f8806de-8681-11e8-8981-7cf240edbbbd.png)

so it is known by the developers that you can't change the Apperance.

But that would not not be a bug/problem as long as this Look&Feel would work on every OS.

**Comment by tobiasdiez** [comment]
I cannot confirm the issue (with the most recent development version and on Windows)

**Comment by bernhard-kleine** [comment]
But drag and drop an entry (some entries) into a group is no longer possible:
JabRef 5.0-dev--snapshot--2018-07-15--master--a44d31668
Windows 7 6.1 amd64 
Java 1.8.0_181

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by JoKalliauer** [comment]
@Siedlerchr 
I tried with:

    JabRef 5.0-dev--snapshot--2018-08-24--master--f43b9c7e8
    Linux 4.15.0-32-generic amd64 
    Java 1.8.0_181

and my desktop still freezes (have to open a virtual terminal to kill java)

**Comment by JoKalliauer** [comment]
@Siedlerchr  https://github.com/JabRef/jabref/issues/4233#issuecomment-415806299 
Thanks: `java -jar -Djavafx.embed.singleThread=true JabRef.jar` worked with:

    JabRef 5.0-dev--snapshot--2018-08-24--master--f43b9c7e8
    Linux 4.15.0-33-generic amd64 
    Java 1.8.0_181
