### ISSUE TITLE
added file link has absolute instead of relative path

### ISSUE THREAD

**Issue by lisifdeoral** [JabRef/jabref#4241]
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.3.1 on Windows 10

Jabref generates an absolute path to file if the relative path would "climb" the directory tree

Steps to reproduce:
0. assume you have a file "C:\foo\file.pdf"
1. set file directory (whether main, general, or user-specific) to "C:\bar"
2. right click on any JabRef entry -> select "Attach file"
3. navigate to and select "C:\foo\file.pdf"
4. The path to file will be stored in absolute format "C:\foo\file.pdf" instead of relative "..\foo\file"

Note that JabRef (at least on Windows) still handles correctly relative paths which include "..\" (or start with "\\") as long as you type them yourselves.

**Comment by Siedlerchr** [comment]
Duplicate of  #4201 

Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by lisifdeoral** [comment]
Thanks for the very quick response!

I tested the latest master and the issue does not seem to be solved.
(I apologise for not having tested the master before posting!)

Version:
JabRef 5.0-dev--snapshot--2018-07-25--master--077fdacc2
Windows 10 10.0 x86 
Java 1.8.0_171

I can provide further info if needed.

**Comment by Siedlerchr** [comment]
Hi,

than ks for your quick response. The relative file directory is only partially possible.,

**Comment by Siedlerchr** [comment]
I found the issue. The file only gets relativized if you hit the browse button.
Already an idea how to fix this, but I am off until sunday.

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by dropbearII** [comment]
I just tested the latest master and development snapshop. The file attachment is still not working. I've tried adding via General -> "+" and via right clicking on the enry.

Win 7, 64bit
 https://builds.jabref.org/master/JabRef-5.0-dev--snapshot--2018-11-21--master--c19f3a46a.jar
Java version 8.0.1910.12

**Comment by tobiasdiez** [comment]
@dropbearII what exactly is not working for you?
