### ISSUE TITLE
Fix exporter tests

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4272]
As was recognized in #3959, some of the exporter tests are not working correctly.

**Comment by Siedlerchr** [comment]
MsOffice is resolved. 
ModsExporter needs to be checked again

**Comment by tobiasdiez** [comment]
The tests are now fixed thanks to @NivedhaSunderraj.

**Comment by Siedlerchr** [comment]
@NivedhaSunderraj  Which ones are still failing?

**Comment by NivedhaSunderraj** [comment]
@tobiasdiez  testPerformExport and testImportAsModsAndExportAsMods are still not fixed and they both have same issue I think

**Comment by Siedlerchr** [comment]
@NivedhaSunderraj  Could you investigate what exactly is failing? Maybe the format of the xml files has changed? That was the case for the MsOffice stuff

**Comment by NivedhaSunderraj** [comment]
@tobiasdiez  Sure I'll look into it 👍

**Comment by NivedhaSunderraj** [comment]
@tobiasdiez Looks like the temp file created has an attribute 'xsi:type="mods:stringPlusLanguagePlusSupplied"' , but this is not in the xml files. And this caused the error... Do I add the attribute to xml file? Or modify export ?

**Comment by tobiasdiez** [comment]
I'm not too familiar with the Office export, but this attribute does not seem to be utterly important and I'd hence say remove it from the reference files.

**Comment by NivedhaSunderraj** [comment]
@tobiasdiez the xml reference files don't have the attribute ... It is being added when exporting it. So should I add the attribute in the reference xml file?

**Comment by tobiasdiez** [comment]
Ah ok, I misunderstood you there. Yes, then please add it!

**Comment by NivedhaSunderraj** [comment]
@tobiasdiez  Sure 👍
