### ISSUE TITLE
Stange rendering of \textsuperscript in entry list

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#4424]
As seen from the screenshot, `5\textsuperscript{th}` is rendered correctly in the preview but incorrectly in the list of entries.

![capture](https://user-images.githubusercontent.com/865866/47611903-4d6cc880-da6f-11e8-92bb-66e967e5b40d.PNG)

The database content is:
```
@Article{Tamis-LeMonda2017,
  author       = {Catherine S. Tamis-LeMonda and Rufan Luo and Karen E. McFadden and Eileen T. Bandel and Claire Vallotton},
  title        = {Early home learning environment predicts children’s 5\textsuperscript{th} grade academic skills},
  journaltitle = {Applied Developmental Science},
  date         = {2017},
  pages        = {1--17},
  doi          = {10.1080/10888691.2017.1345634},
}
```

JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_191

Note that superscript t and h exist in Unicode: 5ᵗʰ

Also, the database is flagged as modified, even if I only loaded it.
Thanks for looking!
mario

**Comment by crystalfp** [comment]
If I save the database (flagged as modified) JabRef adds the `@Comment` and `% Encoding` lines, but the superscript disappears:
```
% Encoding: UTF-8

@Article{Tamis-LeMonda2017,
  author       = {Catherine S. Tamis-LeMonda and Rufan Luo and Karen E. McFadden and Eileen T. Bandel and Claire Vallotton},
  title        = {Early home learning environment predicts children’s 5 grade academic skills},
  pages        = {1--17},
  date         = {2017},
  doi          = {10.1080/10888691.2017.1345634},
  journaltitle = {Applied Developmental Science},
}

@Comment{jabref-meta: databaseType:bibtex;}
```

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by crystalfp** [comment]
Much worse. The superscript disappears everywhere (entry list, preview, edit form) and, if I save the database, even there has disappeared.
I used JabRef--master--latest.jar dated 2018-10-28

**Comment by Siedlerchr** [comment]
Please try again with the latest development version:
On Windows 10 looks fine to me 
![grafik](https://user-images.githubusercontent.com/320228/47863239-1728a380-ddf7-11e8-8f05-2987412546e0.png)

**Comment by crystalfp** [comment]
OK, fixed in the November 1st version.
Thanks a lot!
mario

**Comment by monikajaskolka** [comment]
I am still experiencing this issue.
JabRef 5.0--2020-03-06--2e6f433
Mac OS X 10.14.6 x86_64 
Java 13.0.2

![textsuperscriptissue](https://user-images.githubusercontent.com/6617546/77800627-96062800-704d-11ea-8aee-c2a2904eff8a.png)
