### ISSUE TITLE
Edit group: Color code item is cut at half the size

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4678]
JabRef 5.0-dev--snapshot--2019-02-19--master--1b6c7b5b9
Windows 7 6.1 amd64 
Java 1.8.0_201

- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. In the edit group window the color code is only half visible, the color picker itself works
2. ...
3. ...
![grafik](https://user-images.githubusercontent.com/9216487/53082750-cf40a000-34fd-11e9-8f55-08231ce2f018.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Should be fixed in the latest master:
![grafik](https://user-images.githubusercontent.com/320228/54474647-9edfdf00-47e7-11e9-9705-b8061cb4eada.png)

**Comment by bernhard-kleine** [comment]
just tested with the JabRef 5.0-dev--snapshot--2019-03-16--master--d7dd41b00, not yet changed

**Comment by bernhard-kleine** [comment]
@Siedlerchr: with the snapshot of 2019-03-18 is still not fully shown. Should be reopened.

**Comment by Siedlerchr** [comment]
This is odd, as you can see in my screenshot from a Windows 10 system it works fine.

**Comment by AEgit** [comment]
I cannot confirm this bug for:

JabRef 5.0-dev--snapshot--2019-03-18--master--52696f04b
Windows 10 10.0 amd64 
Java 1.8.0_201

So this might be a Windows 7 problem?
But while checking for this bug, I found another one, which I will report elsewhere.

**Comment by bernhard-kleine** [comment]
I have the textsize in the Windows adaption set to 125%, but when I set it to 100% the text is still cut in half.
Setting the textsize in Jabref smaller has not equally any effect.

**Comment by AEgit** [comment]
@bernhard-kleine 
Just a wild guess: If it is not a Windows 7 problem (we would need another Windows 7 user to confirm this), it might be related to display size and/or resolution. Currently I am using a 24 inch screen with a resolution of 1920x1080. What about your display setup?

**Comment by bernhard-kleine** [comment]
I have a 1920x1200 screen

**Comment by AEgit** [comment]
Hmmm ok, then it is probably not a display issue (I thought you might have a very small monitor, but that is obviously not the case).
So maybe it is Windows 7 then, that causes the issue? Let's see if we can find another user with Windows 7 and JabRef installed.

**Comment by bernhard-kleine** [comment]
Hi, with font size 10, adjusted in Jabref option, the text is fully shown. But with font size 13 it is not!!!! A problem of Jabref obviously!

**Comment by AEgit** [comment]
Ahhh, there we go - I only used the default font size. Yes, if I change the default font size to 13, I get the same issue.

JabRef 5.0-dev--snapshot--2019-03-19--master--90376f40f
Windows 10 10.0 amd64 
Java 1.8.0_201

**Comment by tobiasdiez** [comment]
It's a bug in the library we use for the color picker. I reported it at https://github.com/jfoenixadmin/JFoenix/issues/957. Since there is nothing we can do but just wait until it is fixed on their side, I'll close this issue.
