### ISSUE TITLE
Downloads from the arXiv are marked as HTML files instead of PDF

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#4913]
JabRef version: latest  on  Windows

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Import an entry from the arXiv, say `1207.0408v1` (using Library > New Entry > ArXiv)
2. Go to File tab, right-click link, and select Download
3. The file is downloaded successfully, but has file extension `html` instead of `pdf`. Renaming the file results in a readable pdf through.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment]
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by wenjie-yin** [comment]
Hi, I am still experiencing the same issue using JabRef-5.16-portable_windows from https://builds.jabref.org/master, following manual installation. could you advise on what the problem might be?

**Comment by Siedlerchr** [comment]
@wenjie-yin  I cannot reproduce this, can you tell me how you import the axiv entry?  e..g by New entry or via search? or directly in the entry editor by clicking on download somwhere?

**Comment by wenjie-yin** [comment]
> @wenjie-yin I cannot reproduce this, can you tell me how you import the axiv entry? e..g by New entry or via search? or directly in the entry editor by clicking on download somwhere?

it was through clicking on the firefox plug-in on an arxiv.org/abs/xxxx.xxxxx page.

**Comment by Siedlerchr** [comment]
@wenjie-yin as a workaround you can directly paste the arxiv url on the main table (works with DOI as well) and the entry will be imported correctly
