### ISSUE TITLE
JabRef--master--latest.jar complains about missing string

### ISSUE THREAD

**Issue by ngirard** [JabRef/jabref#5087]
On Ubuntu 18.10, I've successfully launched JabRef-4.3.1.jar using zulu8.38.0.13-ca-fx-jre8.0.212-linux_x64.

But trying to launch JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar gives the following exception:

```
$ /usr/local/lib/zulu8.38.0.13-ca-fx-jre8.0.212-linux_x64/bin/java -jar  ~/JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar
Gtk-Message: 00:19:29.568: Failed to load module "overlay-scrollbar"
00:19:33.743 [JavaFX Application Thread] ERROR org.jabref.JabRefMain - Unexpected exception
java.lang.IllegalStateException: It is not allowed that the toReplace string: '<tt>author=smith and title=electrical</tt>' does not exist in the original string
        at org.jabref.gui.util.TooltipTextUtil.splitReplace(TooltipTextUtil.java:92) ~[JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar:?]
        at org.jabref.gui.util.TooltipTextUtil.formatToTexts(TooltipTextUtil.java:62) ~[JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar:?]
        at org.jabref.gui.search.GlobalSearchBar.setHintTooltip(GlobalSearchBar.java:291) ~[JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar:?]
        at org.jabref.gui.search.GlobalSearchBar.updateHintVisibility(GlobalSearchBar.java:311) ~[JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar:?]
        at org.jabref.gui.search.GlobalSearchBar.<init>(GlobalSearchBar.java:94) ~[JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar:?]
        at org.jabref.gui.JabRefFrame.<init>(JabRefFrame.java:148) ~[JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:50) ~[JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar:?]
        at org.jabref.JabRefMain.start(JabRefMain.java:76) ~[JabRef-5.0-dev--snapshot--2019-06-28--master--47cd33c1b.jar:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863) ~[jfxrt.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326) ~[jfxrt.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$10(GtkApplication.java:245) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Siedlerchr** [comment]
Seems like this is a translation/crowdin sync issue

**Comment by ngirard** [comment]
The problem still occurs with `JabRef-5.0-dev--snapshot--2019-07-09--master--5330a36bf.jar`.

**Comment by Siedlerchr** [comment]
Could you please tell me if you use another as the default (english language)?

**Comment by Siedlerchr** [comment]
@ngirard  I re synced the localization files with crowdin. The issue should be resolved in the most recent build from https://builds.jabref.org/master/

**Comment by ngirard** [comment]
Apologizes for the late reply. For some reason, I wasn't notified by email about your messages.

I'm afraid the problem remains using JabRef-5.0-dev--snapshot--2019-07-15--master--e89d60370.jar.

My locales are in french.

**Comment by Siedlerchr** [comment]
Should be fixed in the next build in a couple of minutes. There was a word translated in the search example which should have not been translated, because JabRef replaces the formatting identifiers and searches for the exact text.

**Comment by ngirard** [comment]
Indeed, working fine now. Thanks for your efforts !
