### ISSUE TITLE
PDF files won't open anymore

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#5253]
JabRef version 5.0-dev

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Clicking on a document icon used to open the associated PDF. Now, the PDF viewer opens and closes immediately. No error is logged.

1. Click on a document icon

**Comment by Siedlerchr** [comment]
Cannot reproduce this under Windows 10. PDF opens fine. Sure the path is correct?

**Comment by j0hannes** [comment]
I have the configured a "main file directory". The "file" entries are just bare file names. If I go to that directory and call the PDF viewer with one of the file names, it will open.

**Comment by stefan-kolb** [comment]
Please check external programs tab in preferences where the paths to PDF viewer etc. are set.

**Comment by j0hannes** [comment]
There are two options under "Open PDF", Adobe Acrobat Reader and Sumatra Reader. None of them is checked. When I click on a document, I see a new instance of Okular, which is the default application that has worked until now. After a couple of seconds this instance disappears; no errors are logged.

**Comment by AEgit** [comment]
JabRef 5.0-dev
Linux 5.0.0-27-generic amd64 
Java 1.8.0_222

Cannot confirm this issue. What I do note with the snap version I am using, however, is that every time I want to access a PDF file, I have to accept the following message:


```
Allow opening file?

Allow snap "jabref" to open file "/path/to/my/pdf/my.pdf"?

This dialogue will close automatically after 5 minutes of inactivity.
```
My PDFs are stored on a NTFS formatted drive (I am running Linux and Windows in a dual-boot configuration) which is mounted to /media/myuser. To access that folder using the snap version of JabRef it was necessary to use the removable-media option, i. e. `sudo snap connect jabref:removable-media`. This allows JabRef to access the drive/folder. However, the message reported above will still appear every time JabRef tries to open an associated file stored on the NTFS formatted drive. Is there a way so that I only have to accept this message once? Is this even a JabRef issue or is this something related to the general implementation of snap?
See also:
https://forum.snapcraft.io/t/always-allow-opening-file/5646/2
https://askubuntu.com/questions/1051207/snap-how-to-grant-permament-permission-to-read-folder

**Comment by j0hannes** [comment]
With the most recent dev snapshot (JabRef 5.0-dev--snapshot--2019-09-05--master--99a0a7a8d), PDF files open instantaneously. Have there been any recent changes on that code?

I think, we may close the ticket.

**Comment by amontero90** [comment]
This behaviour is still present in the with the deb package in 

https://builds.jabref.org/master/jabref_5.0.0-1_amd64.deb

Built in 2019-10-21

**Comment by j0hannes** [comment]
The same version from sources works for me.

**Comment by amontero90** [comment]
And by sources you mean.. exactly the same link I provide above?

I just tested again on a fresh installation of Kubuntu 19.10. The behaviour is exactly the one that j0hannes described in the first comment. I can also reproduce what AEgit described with the snap package even though my files are stored in the same unit as JabRef.

**Comment by j0hannes** [comment]
These are the sources: https://builds.jabref.org/master/JabRef-portable_linux.tar.gz

Shouldn't make a difference to what you find in the deb package, though.

**Comment by amontero90** [comment]
Update: seems to be a permissions problem. The path for the application in my system is `/opt/jabref/bin/JabRef`. However, if I run `sudo /opt/jabref/bin/JabRef` it is possible to open PDF files as usual. This might offer some workarounds.

**Comment by j0hannes** [comment]
To my surprise I couldn't open PDF files on my other machine, which is set up identically to the one where it worked after upgrading. Ther error message was `kf5.kio.widgets: Malformed URL: ""`.

After changing the standard library path for PDFs from a symlink to the real path, opening those PDFs worked again. It seems as if symlinks are problematic for JabRef or one of its components. Running it as root might circumvent the problem that symlinks are causing - just a wild guess.

**Comment by Siedlerchr** [comment]
Thanks for the hint with symlinks . There might be an option which needs to be passed to the path methods 
and also the hint for snaps.

**Comment by amontero90** [comment]
@j0hannes... I think they are different (although possibly related) errors. The one that you mention seems to be a path issue. A very similar error occurs if your links (the links that JabRef uses to the files) are broken; in particular, when the file path is not well configured. The links in my situation are well configured, since I can open pdf files without changing them. Anyways, thanks for the input.

**Comment by Krzmbrzl** [comment]
I ran into (seemingly) the same issue on KDE Neon. If I try to open a PDF, I only see the Okular icon jumping around my cursor but then it vanishes without Okular starting.

I also found out that if I have Okular open already, I can open PDFs without problem (they appear in new tabs in the same Okular instance as this is the way I have Okular configured).

Info from JabRef's about-page:
```
JabRef 5.0.0-dev--2019-10-25----681d6aa6f
Linux 5.0.0-32-generic amd64 
Java 12.0.2
```

**Comment by t-morales** [comment]
I have the same problem. 
I downloaded the latest snapshopt of Jabref and I cannot get to open any pdf. 
I tried with okular open as described by Krzmbrzl but the pdf not opening for me
I tried to run jabref with sudo. Now, when I click on the pdf icon, the pdf file opens but with gimp.

Any ideas on how to resolve the problem?

**Comment by Siedlerchr** [comment]
Hmm. As far as I remember JabRef simply uses xdg-open as

**Comment by Krzmbrzl** [comment]
@t-morales did you try using xdg-open to open the PDF from the command-line?

**Comment by t-morales** [comment]
I tried with xdg-open:
- Running with normal user it opens pdf correctly
- Running as sudo or root, I have seen that it was not correctly configured to okular, so I have set now okular as default for root
- Now, when I run JabRef with sudo, pdf opens correctly with okular
- When I run JabRef as normal user, still the same behavior, the pdf does not open

**Comment by t-morales** [comment]
Hi:
Anyone has any more information on this topic?
Up to now, the only workaround I found is to run JabRef with sudo.

**Comment by Siedlerchr** [comment]
JabRef's code is to call xdg open or a configured application. https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/desktop/os/Linux.java

Could you please specify if it makes any difference from where you open the pdf?
e.g. from the maintable or from the general tab

**Comment by t-morales** [comment]
It makes no difference. Using the main table or the general tab does not open pdf file.
I do not obtain any error message or information on what the problem is. 
The only thing that works for me is to run jabref with sudo command. Then, clicking on the pdf icon will open it.

**Comment by Siedlerchr** [comment]
I tested it today in my Ubuntu VM Ubuntu 18.04 with Xfce and Atril Document Viewer  and it works fine.

JabRef 5.0-beta.354--2020-01-18--2612e22
Linux 4.15.0-62-generic amd64 
Java 13.0.2

JabRef is installed under /opt/jabref  from the deb package. 
I'm not a LInux expert. @LyzardKing  Any idea on why xdg open apparently requires sudo?

**Comment by Krzmbrzl** [comment]
Maybe the problem then is only occurring, if using Okular as a viewer? :thinking:

**Comment by t-morales** [comment]
I changed the viewer to atril and it works.
I confirm that the problem is when I set okular as pdf viewer.
Any ideas why it is so? It should just run the external program, no mater which pdf viewer is set as default.

**Comment by Krzmbrzl** [comment]
Very interesting. I'd like to stress though that when running `xdg-open` on my machine from the command line, it opens just fine in Okular. So it seems to not be a problem with `xdg-open` and Okular per se

**Comment by t-morales** [comment]
Then that is even more strange.
These are the details of my configuration:

JabRef 5.0-beta.357--2020-01-18--6319d05
Linux 5.3.0-26-generic amd64 
Java 13.0.2

I am using Kubuntu 19.10 and JabRef downloaded from 
https://builds.jabref.org/master/JabRef-5.0-portable_linux.tar.gz

**Comment by LyzardKing** [comment]
I have the jabref deb working with the okular at the moment.
It works without problems if I set okular as the system default pdf viewer

**Comment by Krzmbrzl** [comment]
Does JabRef somehow interact with the system via its own pseudo user? If that'd be the case, then maybe the problem is that `xdg-open` doesn't work with that specific user account...

**Comment by Siedlerchr** [comment]
Please be aware that the java Runtime.exec() is not a shell! It's much more limited: 
https://stackoverflow.com/a/31776547

So I guess this is some okular specific issue? 
I could only add some code to display results from error or output stream in JabRef. maybe this gets some insights

**Comment by Krzmbrzl** [comment]
Did someone try to write a small standalone Java application that uses `exec` and `xdg-open`to open a PDF via Okular?

**Comment by LyzardKing** [comment]
In ubuntu-mate I tried running a Java REPL (JShell) with the following command:
`Runtime.getRuntime().exec("xdg-open /home/galileo/Documents/justifier.pdf")`
And it succesfully opened  okular (the default pdf viewer in my system settings).

**Comment by t-morales** [comment]
I am not a java expert, but it seems that this is java related. I have tried the following program in java:

```
import java.io.BufferedReader;
import java.io.InputStreamReader;

public class testprog {
    public static void main(String args[]) {
        String s;
        Process p;
        try {
            p = Runtime.getRuntime().exec("xdg-open <path-to-pdf>");
        } catch (Exception e) {}
    }
}
```

When the default application is set as okular, the pdf does not open.
When I switch to atril, it works.

**Comment by t-morales** [comment]
If anyone knows where or how I could get more information on this topic I would be grateful.

**Comment by tobiasdiez** [comment]
You can try to see if there is an error message using
```java
BufferedReader in = new BufferedReader(new InputStreamReader(p.getErrorStream()));
```
https://stackoverflow.com/a/8150065/873661

The second part of the answer (using ProcessBuilder) also might be worth a try.

**Comment by LyzardKing** [comment]
@t-morales 
That simple program works on my system, so I don't think it's a java issue.

**Comment by t-morales** [comment]
So, I think that I am close to know what is happening. For some reason, there is an error message that is obtained: 
`discarding "Send SMS via KDE Connect." ("ShareUrl")`
But know, using the extra commands given by @tobiasdiez, the pdf opens with okular.
What I mean is that the code
```
import java.io.BufferedReader;
import java.io.InputStreamReader;

public class testprog {
    public static void main(String args[]) {
        String s;
        Process p;
        try {
            p = Runtime.getRuntime().exec("xdg-open <path-to-pdf>");
            BufferedReader in = new BufferedReader(new InputStreamReader(p.getErrorStream()));
            String line;
            while ((line = in.readLine()) != null) {
                System.out.println(line);
            }
	    p.waitFor();
	    System.out.println("ok!");

    in.close();
        } catch (Exception e) {}
    }
}

```
will open the pdf.

My guess is that the previous code is given and error which is not handled and then okular is closed, while this code is treating correctly the error or warning messages. If that makes sense.

**Comment by Krzmbrzl** [comment]
Would be kinda weird, but I vues it wouldn't be unheard of xD
You mentioning KDE brings to my mind that maybe this is a KDE specific bug as I am using KDE as well. Did someone encounter this bug with a different desktop environment?

**Comment by t-morales** [comment]
Thank you so much for your help. I now have a modified version of JabRef that works!

What I did is to edit the file src/main/java/org/jabref/gui/desktop/os/Linux.java and replace

`Runtime.getRuntime().exec(cmdArray);`
by

```
Process p;
p = Runtime.getRuntime().exec(cmdArray);
BufferedReader in = new BufferedReader(new InputStreamReader(p.getErrorStream()));
String line;
line = in.readLine();
```
Probably not a pretty solution, but as I said I am not familiarized with java. 
Now the pdf files open correctly with okular.

**Comment by Siedlerchr** [comment]
@t-morales  Glad that it works. It would be really helpful for all others, if you could open a Pull Request with your changes. see [Contributing](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md) for some details, e.g. just create a fork and a branch.

**Comment by t-morales** [comment]
OK, I hope I did it correctly: [#5855](https://github.com/JabRef/jabref/pull/5855)
Nevertheless, it would be great if someone with better understanding took a look at the proposed solution. It was more or less a trial and error solution.

**Comment by tobiasdiez** [comment]
Thanks to @t-morales this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by w1th0utnam3** [comment]
Hi, I have essentially the same bug but it still occurs with the latest JabRef snapshot `JabRef 5.0-beta.386--2020-01-28--3579d3d`. I changed my default PDF reader from Okular to Evince and it still does not open. It just shows that the respective PDF reader is opening in the taskbar and then it just disappears. Running `xdg-open ...pdf` in a terminal works and opens Okular/Evince. I'm on Kubuntu 19.10, KDE Plasma 5.17.5, KDE Frameworks 5.66.0.

Any ideas what I can try to do to help?

**Comment by t-morales** [comment]
Hi @w1th0utnam3 
Try just the small java code: 
```
import java.io.BufferedReader;
import java.io.InputStreamReader;

public class testprog {
    public static void main(String args[]) {
        String s;
        Process p;
        try {
            p = Runtime.getRuntime().exec("xdg-open <path-to-pdf>");
            BufferedReader in = new BufferedReader(new InputStreamReader(p.getErrorStream()));
            String line;
            while ((line = in.readLine()) != null) {
                System.out.println(line);
            }
	    p.waitFor();
	    System.out.println("ok!");

    in.close();
        } catch (Exception e) {}
    }
}
```
That gave me more insight on what was not working.

**Comment by w1th0utnam3** [comment]
Thanks @t-morales.
1. It works with Evince as a default pdf viewer and it prints
```
Icon theme "gnome" not found.
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/16x16/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/24x24/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/32x32/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/48x48/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/scalable/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.

(process:15115): Gtk-WARNING **: 10:05:52.266: Locale not supported by C library.
        Using the fallback 'C' locale.
ok!
```
But I don't think these errors are relevant for the problem.
2. It does not work with Okular. The Java program instantly returns and prints
```
Icon theme "gnome" not found.
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/16/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/22/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/24/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/32/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/48/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/64/"
Invalid Context= "stock" line for icon theme:  "/usr/share/icons/ubuntu-mono-dark/stock/128/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/8x8/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/16x16/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/16x16/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/22x22/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/24x24/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/24x24/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/32x32/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/32x32/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/48x48/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/48x48/ui/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/256x256/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/512x512/legacy/"
Invalid Context= "Legacy" line for icon theme:  "/usr/share/icons/Adwaita/scalable/legacy/"
Invalid Context= "UI" line for icon theme:  "/usr/share/icons/Adwaita/scalable/ui/"
Icon theme "Mint-X" not found.
Icon theme "elementary" not found.
Icon theme "gnome" not found.
Icon theme "gnome" not found.
ok!
```
Meanwhile, it shows the same behavior as in JabRef (looks like it is opening but then disappears). But I cannot see any output from Okular in the terminal because the Java program returns without waiting for Okular.

It's a little bit weird that this Java program works with Envince but it does not work in JabRef.

**Comment by t-morales** [comment]
For me it worked with okular with that program. 
Maybe try to fix all those warnings? 
It seems that it cannot find the icons and themes, so I would try to install them to see if that changes anything

**Comment by w1th0utnam3** [comment]
Huh, so switching my system icon theme to a standard theme (like Breeze) fixes all problems because then all these warnings/errors disappear. It also works in JabRef then.

I'm using the Candy icons theme from the KDE store. These warnings are caused by many custom icon packs, e.g. see https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/418. Installing the missing icon themes does not really help because installing one theme adds new errors and I got stuck with "Icon theme "gnome-colors-wise" not found." which I couldn't find anywhere to install. I continued by modifying the `index.theme` file of the icon pack and removed the dependencies on the other themes so I'm just left with the `Invalid Context=` warnings. But then it still does not work. It seems like Okular won't start from Java when anyhting appears in `stderr`. So this has to be a bug somewhere, although I'm not sure where exactly.

**Comment by w1th0utnam3** [comment]
So I removed some further dependencies/inheritances from the `index.theme` file of the icon theme and now all warnings are gone and it works from Java/JabRef again. But I still don't get why this prevents Okular from opening. I don't know if it's a bug with Okular, `xdg-open` or some weirdness of Java's `exec`.

**Comment by w1th0utnam3** [comment]
So I found a workaround in Java. Instead of using `exec` with `xdg-open` directly it is possible to use `Desktop.getDesktop().open(..)`:

```java
import java.awt.Desktop;
import java.io.File;

public class testprog {
    public static void main(String args[]) {
        try {
            Desktop.getDesktop().open(new File("<path to pdf>"));
        } catch (Exception e) {}
    }
}

But I'm not sure if using this might not be possible in JabRef due to Java version restrictions.
```
