### ISSUE TITLE
Java issue with snap installed jabref on Ubuntu 18.04

### ISSUE THREAD

**Issue by lizliz** [JabRef/jabref#5401]
JabRef version 5.0-dev on Ubuntu 18.04 (I've had similar issues on my computers with 19.04 installed)

- [ X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I’ve been an avid Jabref user for a long time, but the latest updates have made it basically non-functional for me. Doing almost anything results in an error to the effect of “Uncaught exception occured… TypeError: undefined is not a function”. This includes searching, clicking on an entry, attaching a file to an entry, and typing in an entry (which is the most annoying since it throws 2-5 of those errors every time I type a letter…).

I have to guess this is a java version issue but I can’t seem to determine from the forums what the fix might be. What should I be looking for to debug this problem? Since older versions of jabref seem to have lost their import via doi functionality, I really need to get jabref 5 working.

1. Basically anything.... clicking on entries does it sometimes, searching does it sometimes, auto-attaching a file does it sometimes....

<details>
  <summary>Example error output</summary>
  
netscape.javascript.JSException: TypeError: undefined is not a function
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at com.sun.webkit.WebPage.executeScript(WebPage.java:1439)
	at javafx.scene.web.WebEngine.executeScript(WebEngine.java:982)
	at org.jabref.gui.preview.PreviewViewer.highlightSearchPattern(PreviewViewer.java:103)
	at org.jabref.gui.preview.PreviewViewer.lambda$new$260(PreviewViewer.java:94)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.web.WebEngine$LoadWorker.updateState(WebEngine.java:1260)
	at javafx.scene.web.WebEngine$LoadWorker.dispatchLoadEvent(WebEngine.java:1371)
	at javafx.scene.web.WebEngine$LoadWorker.access$1200(WebEngine.java:1253)
	at javafx.scene.web.WebEngine$PageLoadListener.dispatchLoadEvent(WebEngine.java:1240)
	at com.sun.webkit.WebPage.fireLoadEvent(WebPage.java:2400)
	at com.sun.webkit.WebPage.fwkFireLoadEvent(WebPage.java:2244)
	at com.sun.webkit.Timer.twkFireTimerEvent(Native Method)
	at com.sun.webkit.Timer.fireTimerEvent(Timer.java:83)
	at com.sun.webkit.Timer.notifyTick(Timer.java:64)
	at javafx.scene.web.WebEngine$PulseTimer.lambda$static$10(WebEngine.java:1201)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:347)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:374)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$346(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
</details>

**Comment by Siedlerchr** [comment]
This issue is solved in the latest development version and should be also in the latest snap version edge

**Comment by lizliz** [comment]
Just ensured that I have the latest snap beta version install, and still having the same issues.

Uninstalled that and downloaded the jabref_5.0.0-1_amd64.deb file from https://builds.jabref.org/master/, but this installed 4.3.1 instead of 5.0.

**Comment by Siedlerchr** [comment]
Hi,
the error is related to the search highlighting in the entry preview. It has been fixed in the 
if you want to use the snap you need to use the `edge` version, e.g. `sudo snap install jabref --edge`
The bug was fixed recently

I will check the deb file as well

**Comment by lizliz** [comment]
That install doesn't run for me for some reason: 

```
liz@galadriel:~
$ jabref
/snap/jabref/550/bin/desktop-launch: line 574: /snap/jabref/550/jabref/bin/JabRefMain: No such file or directory
```

**Comment by Siedlerchr** [comment]
Sorry for the inconvenience, we are working on getting the snap build running again.
In the meantime you can use that debian package. It will be installed Jabref to /opt/ 
I tested it in my  Ubuntu VM.

**Comment by jusneuma** [comment]
Hi, I am getting the same error as lizliz

/snap/jabref/550/bin/desktop-launch: line 574: /snap/jabref/550/jabref/bin/JabRefMain: No such file or directory

Has this been solved?
I am using Fedora 30 and I have trouble to run any jabref version later than 3.8 because of JavaFX related issues. I read that the snap edge version could work with Fedora, but now I run into this issue.

**Comment by LyzardKing** [comment]
The snap version in the store is not up to date, since we are waiting for some extra permissions before we can upload the new version.
Meanwhile you can download the snap from https://builds.jabref.org/master/
and install with `snap install jabref_5.0.0_amd64.snap --dangerous`
It will not auto-update when the full version is uploaded to the store..so you should check that
from time to time.
Or you could try the rpm

**Comment by jusneuma** [comment]
Thank you for the reply. Unfortunately, I cannot install that version.
`snap install jabref_5.0.0_amd64.snap --dangerous`
`error: cannot open: "jabref_5.0.0_amd64.snap"`
Any idea why that might be? Sorry, I am new to snap, maybe it has an easy solution?

**Comment by jusneuma** [comment]
> Or you could try the rpm

The rpm version does work! Thanks for that!

**Comment by LyzardKing** [comment]
To install the snap you first have to download it, then run the install command in the same directory..
It should work.. let me know if you try again..

**Comment by AEgit** [comment]
JabRef 5.0--2020-03-08--93de138
Linux 5.3.0-40-generic amd64
Java 13.0.2

The issue with the snap version might be solved in the current version. Try `sudo snap install --edge jabref` and then afterwards `snap refresh --devmode jabref`. With these commands I managed to get the snap version of JabRef working.
@jusneuma and @lizliz : Can you check whether the current snap version works for you?

**Comment by lizliz** [comment]
Fabulous! So far, everything seems to be working again! And DOI inputs work again! Oh my goodness, I'm so happy!

I only ran `sudo snap install --edge jabref`, didn't do the refresh command and it's working fine.  What does that second command do? Do I need to do that?

**Comment by AEgit** [comment]
If the snap works for you without having to invoke the `--devmode`, then you probably do not need to do this. Switching to/updating a snap in developer mode does not enforce certain security policies that are usually followed by snap packages (can make testing of an application easier).

**Comment by koppor** [comment]
I think, this should also be solved in the stable version distributed today. This is JabRef version 5.0. @lizliz please reopen if the issue persists.
