### ISSUE TITLE
Changes in entry preview are not saved

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6447]
JabRef 5.1--2020-05-04--b5599c9
Linux 4.9.0-12-amd64 amd64 
Java 14.0.1

Changes in the entry preview format are accounted for _only_ after restarting.

Note 1:  may seem similar to issue #5464, but the present issue is about _the content_ of the preview.
Note 2: issue is present with "Show preview as tab in entry editor" checked or unchecked.

1. Create a file with the following entry and save it
```
@Article{MyKey,
  author    = {Author1, Surname1 and Author2 Surname2},
  journal   = {The Journal title},
  title     = {The title of the article},
  year      = {2020},
  number    = {12},
  pages     = {1-100},
  volume    = {15},
 }
```
2. Go to Options -> Preferences -> Entry preview
3. Select "Preview" in the column "Selected"
4. Click on the Edit tab
5. Change
`\begin{journal} <em>\format[HTMLChars]{\journal}, </em>\end{journal}`
into
`\begin{journal} <em>\format[HTMLChars]{\journal},HereIsMyChange </em>\end{journal}`
6. Go to the preview Tab.
    ==> The preview is updated accordingly.
7. Click on save
8. Edit the entry
The preview shows: 
![Capture du 2020-05-08 15-26-09](https://user-images.githubusercontent.com/6931104/81410004-5a787680-9140-11ea-9daa-228aeb24c57e.png)
   `HereIsMyChange` is not displayed ==> The preview is NOT updated.
8. Close and reopen JabRef
9. Edit the entry
The preview shows: 
![Capture du 2020-05-08 15-20-54](https://user-images.githubusercontent.com/6931104/81409511-8a734a00-913f-11ea-80b7-48a952885730.png)
     `HereIsMyChange` is displayed  ==> The preview is updated NOW.

**Comment by Siedlerchr** [comment]
Thanks for the report. Does the Preview update if you close and reopen the entry editor?

**Comment by mlep** [comment]
No.
And it does not update if I switch tabs (between already-open files).
But the preview get updated if I close and reopen a file (but only for this file. Not for the ones in the other tabs).

**Comment by dimitra-karadima** [comment]
@Siedlerchr I am interested in this issue. Can you give me any suggestions or any relevant code where the bug might be?

**Comment by Siedlerchr** [comment]
@dimitra-karadima  Some points: PreviewTab (in the preferences) as well and for the entry editor it might be the PreviewPanel. Probably that the PreviewPreferences are not reloaded in the PreviewPanel when a new style or a modified style is saved

Maybe @leitianjian can help you a bit, she/he worked recently in that area

**Comment by dimitra-karadima** [comment]
@Siedlerchr thanks for the guidance! I will check it out.

**Comment by dimitra-karadima** [comment]
My point of view was to find out where the new changes are being saved in order to update there the PreviewTab. I have found that this happens in https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java#L204 so I made an instance of PreviewPanel in order to update Layout, but it didn't work. I don't know if it is that I created a new Object or it was the wrong thought. @Siedlerchr or anyone else any thoughts?

**Comment by leitianjian** [comment]
Hi, I think this bug is hard to locate, I also stuck in it. If you don't mind, I will fix this bug. If you are still working on it, keep going on, We can discuss it according to your progress. Sorry for my late reply. I do not receive any notification about I was mentioned. Sorry again.

**Comment by dimitra-karadima** [comment]
@leitianjian I am not working on it because I am kinda stuck. All I have found was what I mentioned above. You can either work on it or we can work together and try to find the solution together. It's up to you.

**Comment by leitianjian** [comment]
Thanks for your kindness. In fact, I find that your path is not exactly correct. We should not initialize another object of PreviewPanel which is JavaFX Vbox. I think we should modify some code to let the PreviewPanel content update after saving the preferences, which is a little difficult and deep tasks. The things I'm doing now is to figure out how the preview showing on the EntryEditor, and trying to give an elegant solution to update the preview. If you are still interested in it. Feel free to ask, we can work on this bug together.

**Comment by Siedlerchr** [comment]
Thanks to @leitianjian  this should be fixed

**Comment by mlep** [comment]
Sorry for the delay in testing the fix.
The behavior changed, but I am afraid **the issue is not fixed**.
Now (JabRef 5.1--2020-06-09--595f085), the preview cannot be redefined: The changes in the preview (carried out at step 5) are not saved (after step 7). When I go back to the preferences, my changes in the  preview code are not recorded.

**Comment by mlep** [comment]
ping @Siedlerchr @leitianjian

**Comment by teertinker** [comment]
Hello,
may it is helpful to change to topic of the bug. I just wanted to report a new bug and did find this one only by accident. Maybe something like "Changes in entry preview are not saves"

**Comment by Siedlerchr** [comment]
Still reproducible in the current dev version. Problem is that the chosenListProperty does not know when the preview layout changed. probably need to add a property to that as well

**Comment by Siedlerchr** [comment]
The issue is now finally resolved in the latest master (currently building)

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by AtrusRiven** [comment]
Works in ´5.2--2020-11-06--2f27dd3´ and `5.2--2020-11-07--df80c13` (Win 10, `Java 1.8.0_271-b09`). Thanks for fixing!

**Comment by teertinker** [comment]
Can also confirm that it works.

**Comment by mlep** [comment]
Fixed, indeed. Thank you @Siedlerchr!

**Comment by AtrusRiven** [comment]
Every time I open JabRef something in the customized entry preview style I have already changed many times is reset again.
- Instead of
`\begin{comment}<BR><BR><b>Comment: </b>\format[HTMLChars]{\comment}\end{comment}`
- the following reappears again:
`\begin{comment}<BR><BR><b>Comment: </b>\format[Markdown,HTMLChars]{\comment}\end{comment}`

So, `Markdown` keeps reappearing in the `\format[]` command. Where does that come from? If others discover the same problem I unfortunately consider the issue `not solved`.

**Comment by mlep** [comment]
@AtrusRiven Which version of JabRef are you using?
Note: the fix is in the development version (https://builds.jabref.org/master/)

**Comment by AtrusRiven** [comment]
I'm using the actual master build (`5.2--2020-11-10--f5c52a2`).

**Comment by Siedlerchr** [comment]
Indeed, can reproduce this. for some reason it's not saved after a restart or reset on a restart.

**Comment by Siedlerchr** [comment]
@AtrusRiven  You have triggered an edge case, it's the Preferences Migration that is executed on startup that overwrites your changes. Just add a space after the HtnlChars Formatter Name : `\format[HTMLChars ]{\comment}` to prevent an exact match.

https://github.com/JabRef/jabref/blob/b9be53e056d92837d827efc2a70a06ff733ad0b7/src/main/java/org/jabref/migrations/PreferencesMigrations.java#L313-L319

**Comment by AtrusRiven** [comment]
Thanks, now it works. What is this replacement for?

**Comment by Siedlerchr** [comment]
It's a migration if you come from a previous version. E.g. If some internal fields or prefs got renamed 
 Migrations are run on startup. As the newer versions support Markdown,the preview should show that as well.

**Comment by mlep** [comment]
Bug seems to be in JabRef 5.4--2021-11-15--8a3b77b
Linux 4.19.0-18-amd64 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

@Siedlerchr Please, re-open.

**Comment by fl-la** [comment]
> Bug seems to be in JabRef 5.4--2021-11-15--8a3b77b Linux 4.19.0-18-amd64 amd64 Java 16.0.2 JavaFX 17.0.1+1
> 
> @Siedlerchr Please, re-open.

Can confirm, the bug is very annoying. 
JabRef 5.4--2021-12-20--ab44182
Linux 5.15.8-76051508-generic amd64 
Java 16.0.2 
JavaFX 17.0.1+1

**Comment by Siedlerchr** [comment]
@fl-la  Solution/workaround:
>. Just add a space after the HtnlChars Formatter Name : \format[HTMLChars ]{\comment} to prevent an exact match.

**Comment by jpmvferreira** [comment]
I'm facing a similar issue: Whenever to try to edit the Entry Preview, it fails. It doesn't show on the preview tab, by contrast with what the author of this issue is experiencing, and rebooting doesn't make any change whatsoever.

However, using JabRef 5.5 portable, the issue is the same as yours: editing will only take effect after rebooting, and is shown in the preview tab.

Curiously, going back to JabRef 5.4 which is installed system-wide, reveals the edited entry preview, but I still can't edit it.

Also curiously, I found a situation where this does not seem to apply when using JabRef 5.5. 
Currently my customized preview style looks like the following:
```
<font face="sans-serif">
\begin{title}<b>\format[HTMLChars]{\title}</b> \end{title}
\begin{author}<BR>\format[Authors(10, 10, FirstLast, FullName, Sep=,,LastSep= and ),HTMLChars]{\author}\end{author}
\begin{date}<BR>\date\end{date}\begin{edition}, \edition. edition\end{edition}
\begin{comment}<BR><BR><b>Comment: </b>\format[Markdown,HTMLChars]{\comment}\end{comment}
\begin{abstract}<BR><BR><b>Abstract: </b>\format[HTMLChars]{\abstract} \end{abstract}
</font>
```
For some reason, having the `Markdown` setting on the comment creates a lot of unnecessary newlines and, because I'm not planning on using markdown anyways, I decided to edit it out (again, with v. 5.5 portable where I am able to successfully edit the entry preview).
Preview panel shows that the new lines are removed and, surprisingly, changes take effect immediately and I don't have to reboot JabRef, cool!
Once I reboot JabRef, however, my edits are gone! It seems like I'm back to v. 5.4, where I couldn't do the editing.

It seems that, after fooling around, some edits take place immediately, others don't and some aren't even allowed.

This seems like quite a strange bug, and I'm not sure if I'm making myself clear, so feel free to ask me for further information.

System:
- OS: Manjaro
- Kernel: 5.4.169-1
- WM: i3
- Installation method for JabRef: AUR
