### ISSUE TITLE
Libreoffice connection broken in 5.1

### ISSUE THREAD

**Issue by messiem** [JabRef/jabref#6477]
JabRef version 5.1--2020-05-13--98b62ba on Ubuntu 18.04.4 Linux 4.15.0-99-generic amd64 (Java 14.0.1)

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I installed the latest dev version because it fixed another bug I was having (see https://discourse.jabref.org/t/scrolling-by-typing-a-name-does-not-work-in-5-x/1989). This bug is fixed but I noticed I cannot connect to LibreOffice anymore, while it was working just fine with my previous version (5.0–2020-03-06–2e6f433). 

1. Open a LibreOffice document, and the LibreOffice/OpenOffice connection panel in JabRef.
2. Click "connect" (clicking on "manual connect" gives the same thing, and the path is correct).
3. While the connection was almost immediate on the previous version, now it gets stuck on a window "Autodetecting paths..." until I hit cancel. I have not managed to get a libreoffice connection working.

<details>
  <summary>Log File</summary>
  
  ```
(log file was empty)
  ```
</details>

**Comment by tobiasdiez** [comment]
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by messiem** [comment]
I'm sorry, I just tried but the bug is still there. My version is now 
JabRef 5.1--2020-05-14--09111be
Linux 4.15.0-99-generic amd64 
Java 14.0.1

**Comment by Siedlerchr** [comment]
Thanks for reporting, I  just noticed that the build did not deploy correctly and therefore the fix was not yet included. I have triggered a new build https://github.com/JabRef/jabref/runs/674881288 
Should be read in  roughly half an hour.

**Comment by messiem** [comment]
OK this time it worked, thanks so much!!
(now on JabRef 5.1--2020-05-14--46777c2)
