### ISSUE TITLE
DOI not imported from RIS file

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#6530]
JabRef 5.1--2020-05-23--03e3663
Windows 10 10.0 amd64 
Java 14.0.1

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Importing in a biblatex library the attached RIS file does not load the DOI field.

[PMC4756000.txt](https://github.com/JabRef/jabref/files/4686418/PMC4756000.txt)

1. Change the attached file extension back to RIS
2. Import it in a biblatex library
3. Notice the DOI field is empty, but the file contains a DO field.

**Comment by Siedlerchr** [comment]
Thanks for your report.
A quick look in the code revealed that the DOI only gets imported if it starts with doi;
https://github.com/JabRef/jabref/blob/4e220f618a755cb7dc18882653ea46e3ed049c9e/src/main/java/org/jabref/logic/importer/fileformat/RisImporter.java#L314-L318

Seems like it's missing an else case. Ideally it would also be better to use our DOI class for "parsing" the DOI.

PS: Did you know that JabRef has the ability to import entries directly by PMID?
Just New Entry -> Pubmed/Medline -> enter the id

**Comment by braincident** [comment]
For me it seems not necessary to check if the DOI field exactly starts with "doi:", if it is listed in the RIS file, it should be already verified. So importing and loading will just be fine.
Even if the DOI is listed and imported in wrong format, users can still check and correct it in the APP.

**Comment by Siedlerchr** [comment]
This should be now fixed in the latest master (currently building, ready in roughly half an hour)
We know use our internal DOI parser to check for anything that looks like a valid doi (with or without prefix/url) and add the parsed DOI.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by crystalfp** [comment]
On the build/master page there is still the JabRef 5.1--2020-06-04--7cc5747 that has not solved the problem. I'll wait for a new one. Thanks!

**Comment by Siedlerchr** [comment]
Thanks for the hint, the build got canceled by GitHub. I re triggered a new one just now.
https://github.com/JabRef/jabref/runs/745120654

**Comment by crystalfp** [comment]
OK! Version JabRef 5.1--2020-06-06--5676d65 solved the problem. Thanks!
