### ISSUE TITLE
Cannot find linked files

### ISSUE THREAD

**Issue by jhh931** [JabRef/jabref#6698]
JabRef 5.1--2020-07-18--ee2c985
Windows 10 10.0 amd64 
Java 14.0.2
The portable version.

Under the General tab, linked files are reported as 'cannot find' and attempting to open them has no effect. 

In the GUI I see this:
![Untitled](https://user-images.githubusercontent.com/20792626/87862507-3bbd0a00-c951-11ea-9d0c-c43fb51b9f98.jpg)

The Bibtex file portion is

>   file            = {:C\:/Users/hogemajh/AppData/Local/My Local Documents/JEROENX/artikelen/2020/Addanki_2020.pdf:PDF},

And the file 'c:\Users\hogemajh\AppData\Local\My Local Documents\JEROENX\artikelen\2020\Addanki_2020.pdf' exists on my PC.

It's like this for all linked files; this issue did not occur in previous releases.

**Comment by AEgit** [comment]
Just an idea - could you link a file that is found in folder whose path does not contain spaces (in your example "My Local Documents" contains spaces). I remember, that this caused some issues in the past, but I thought it had been fixed in the meantime.

**Comment by jhh931** [comment]
The problem persists for path+file names without spaces.

Also in the now released 5.1 (portable):
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

**Comment by Siedlerchr** [comment]
Hm. Have you changed some fie directory settings? Normally JabRef should store the files as relative links.

**Comment by Santrace** [comment]
I had the same problem, without changing a file directory setting.

It was fixed just by adding the "main file directory" adress, in "Options" ; "Preferences" ; "File".
Now, I can open an article from this file or another.

Thank's for the help,  @Siedlerchr .

**Comment by jhh931** [comment]
At some point I started using absolute file links in combination with leaving "main file directory" empty. This worked fine under 5.0, not under 5.1.

 I now re-introduced a "main file directory" and did a manual serach & replace in my bib files.
With that the issue is solved on my end.
 
As a side note, I found out that the absolute paths still work when using this format:
`  file        = {:c\:\\Users\\hogemajh\\AppData\\Local\\report.pdf:PDF},`
instead of 
`file = {:C:/Users/hogemajh/AppData/report.pdf:PDF},`

(appratently earlier versions of JabRef inserted the double \\ wheras the current version inserts single /).
