### ISSUE TITLE
No cleartype/subpixel rendering in Preview

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#7266]
JabRef 5.2--2020-12-24--6a2a512
Windows 10 10.0 amd64
Java 14.0.2

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

This issue is present on the v5.2 stable.

1. Enable any preview
2. Cleartype settings are not used

Would enhance readability if cleartype/subpixel rendering settings are respected not only in the window but also in the Preview (see screenshot)

![image](https://user-images.githubusercontent.com/10846169/103241989-1519eb00-4955-11eb-8d98-63a2acbf6663.png)

**Comment by DOFfactory** [comment]
Maybe related to #3295

**Comment by Siedlerchr** [comment]
Can you test again with the latest development version? We recently ugpraded javafx. Maybe it's fixed in that.
Can you also please share your customized preview layout to make it easier for us to reproduce the issue?

**Comment by DOFfactory** [comment]
The issue is not fixed. Using the default IEEE preview format, and this is the result:

![image](https://user-images.githubusercontent.com/10846169/105863538-47207a80-5ff1-11eb-932a-4efcacccb0ac.png)

Tested on 

> JabRef 5.3--2021-01-24--ae43548
> Windows 10 10.0 amd64 
> Java 14.0.2 
> JavaFX 15.0.1+1

**Comment by calixtus** [comment]
I wasn't able to reproduce it on windows 10 and java / jfx 16:
Maybe it has been fixed in a recent release of JavaFX? Are you using a HiDPI screen? JavaFX seems to have sometimes problems working with high resolution and scaling...

![grafik](https://user-images.githubusercontent.com/50491877/133137657-c524ef60-dc9a-4986-a405-c4830d1c61f3.png)

**Comment by DOFfactory** [comment]
Yes, it is hidpi screen.
