### ISSUE TITLE
Wiki: Donations : Clarification needed

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#774]
On page https://github.com/JabRef/jabref/wiki/Donations , one can read:

> In case you want to donate regularly, please visit http://www.jabref.org/donations.

Regular donations are not mentioned on the website. Additionally, why to send to the website, considering 1) the wiki has more information and 2) the website send to the wiki?

>In case you live in the EU, you can ask for Oliver's private Email Address to [send money for free] (https://www.paypal.com/de/webapps/mpp/paypal-fees)

Where to ask? Could it be possible to add directly an email address? Strangely, "send money for free" is linked to paypal fees...

**Comment by mlep** [comment]
About regular donations: I believe it relates to: https://github.com/JabRef/www.jabref.org/blob/gh-pages/donations.html

But this page is not part of the current website, right?

**Comment by koppor** [comment]
The regular donations page appeared. Since the move to Jekyll 3.0 by GitHub, this is broken. Refs https://github.com/JabRef/www.jabref.org/issues/11.

**Comment by koppor** [comment]
With the new Jeykll, `donations.html` has been generated both because of `_posts` and `donations.html` in the source. `_posts` won. Therefore, I renamed it to `paypal`: http://www.jabref.org/paypal

Think, all your issues are fixed.

We can also move the whole content to the web page at http://www.jabref.org/#donations if that's better. Or to http://www.jabref.org/dontations (then, we have to remove #donations) somehow.

**Comment by mlep** [comment]
Thank you for sorting out the regular donation stuff.

I believe this issue still need to be resolved, to that the information will be clear for readers:
>On page https://github.com/JabRef/jabref/wiki/Donations 
>>In case you live in the EU, you can ask for Oliver's private Email Address to [send money for free] (https://www.paypal.com/de/webapps/mpp/paypal-fees)

>Where to ask? Could it be possible to add directly an email address? Strangely, "send money for free" is linked to paypal fees...

**Comment by koppor** [comment]
My browser did not safe my last edit. Is it now more clear?

**Comment by mlep** [comment]
Adding a contact surely makes things easier!
But why the text "send money for free" is linked to Paypal?

**Comment by mlep** [comment]
OK, I got it (thanks to google translation)
