### ISSUE TITLE
journalList.mv files collect in /tmp

### ISSUE THREAD

**Issue by protist** [JabRef/jabref#7810]
JabRef version
```
JabRef 5.2.r377.g2497ba4d82--ArchLinux--1
Linux 5.12.9-arch1-1 amd64 
Java 15.0.2 
JavaFX 16+8
```
on Arch Linux

- [x ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. Launch JabRef
2. Monitor `/tmp`
3. Observe the creation of directories and new `journalList.mv` files, such as `/tmp/journal10325059816431707548/journalList.mv`.

Over the course of two days, I have 28 of these directories and files, for a total of 580M. Given I use a tmpfs, this is gradually eating up my RAM.

The template says to paste an "excerpt of log (available in the error console)". I can't find anything called "error console", although in the menus I found `Help` > `View event log`. This was empty. However, I launched jabref from the terminal, and it gave the following output and error.
<details>
  <summary>command-line output and error</summary>

```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Jun 10, 2021 6:11:03 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true

(java:1200853): Gdk-WARNING **: 18:11:07.035: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

</details>

**Comment by koppor** [comment]
Should have been fixed in https://github.com/JabRef/jabref/pull/7811. In a few days, one can try the current development version from https://builds.jabref.org/main/

Currently blocked by signing issues - https://github.com/JabRef/jabref/runs/2798330514?check_suite_focus=true

**Comment by protist** [comment]
Thanks @koppor! I'm building from source, so I've just installed it now. It seems to work perfectly! Good idea to rename the directories. It took a little bit of investigating to work out what was producing the files previously. They are now deleted after quitting as expected. Thank you for the quick fix!

**Comment by btut** [comment]
Sorry, I tried to reproduce with the current main branch but can't. I was probably working with outdated code when I reported the issue still being current.
